### ISSUE TITLE
Defaultní konfigurace importu slovníků pro instanci ontoGrapher

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#1]
Instance ontoGrapher je nakonfigurována odkazem na definici importu slovníků, které jsou dostupné prostřednictvím SPARQL endpointů. Slovník může být importován buď jako sada stereotypů (= profil) nebo jako model.

Konfigurace je v podobě JSON souboru, který bude umístěn na nějaké veřejně dostupné IRI. Default si bude ukazovat na defaultní konfigurační IRI a uživatel si to může změnit.

Defaultní konfig JSON pro instanci ontoGrapheru kterou používáme pro tvorbu SGoV bude vypadat cca takto:

```[
  {
      type: "as stereotypes",
      name: "ZS-GOV",
      endpoint: "https://slovník.gov.cz/sparql",
      language: "cs",
      classIRI: "http://www.w3.org/2004/02/skos/core#inScheme",
      sourceIRI: "https://slovník.gov.cz/základní/glosář",
      labelIRI: "http://www.w3.org/2004/02/skos/core#prefLabel",
      definitionIRI: "http://www.w3.org/2004/02/skos/core#definition",
      stereotypeIRI: ["http://www.w3.org/2002/07/owl#Class"],
      relationshipIRI: ["http://www.w3.org/2002/07/owl#ObjectProperty"],
      attributes: [
        {
          name: "term label",
          iri: rdfs:label,
          type: xsd:string
        },
        {
          name: "search index",
          iri: skos:altLabel,
          type: [xsd:string]
        },
      ]
  },{
      type: "as read only imported model",
      name: "VS-GOV",
      endpoint: "https://slovník.gov.cz/sparql",
      language: "cs",
      classIRI: "http://www.w3.org/2004/02/skos/core#inScheme",
      sourceIRI: "https://slovník.gov.cz/veřejný/glosář",
      labelIRI: "http://www.w3.org/2004/02/skos/core#prefLabel",
      definitionIRI: "http://www.w3.org/2004/02/skos/core#definition",
      classIRI: ["http://www.w3.org/2002/07/owl#Class"],
      relationshipIRI: ["http://www.w3.org/2002/07/owl#ObjectProperty"]
  }
]```

Tento JSON zatím měj na nějaké IRI zde na Githubu klidně. Nastav instanci ontographeru pro ukázky na toto IRI. Když tuto instanci spustím, uvidím ZS-GoV jako sadu stereotypů a VS-GoV jako model. VS-GoV na obrázku najdeš zde: https://opendata.gov.cz/_media/dokumenty:sémantický-slovník-pojmů:c1v2_koncepce_sémantického_slovníku_pojmů.pdf

Importované slovníky je read only.

**Comment by martinnec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontoGrapher](https://trello.com/c/RCIYuzZP/22-pr%C3%A1ce-na-issues-v-ontographer)

**Comment by bindetad** [comment]
V 55199a292570bcfd9c305e74b0405f4749865e26 je implementovaná funkce importu slovníků a práce s více slovníky - uživatel může vybírat mezi elementy jednotlivých slovníků v levém panelu a vybírat typy atributů v detailech vybraného stereotypu.
![image](https://user-images.githubusercontent.com/56399637/67165304-c7cee080-f383-11e9-836e-c37fea1c7ee7.png)

Slovníky se mohou přídávat/odebírat buď ručně v souboru, nebo přes dialogové okno Settings->Vocabularies...

![image](https://user-images.githubusercontent.com/56399637/67165356-2300d300-f384-11e9-861d-32371d310f0e.png)

Elementy komponenta přidává přes SPARQL dotaz. Pokud chcete, mohu upravit funkci pro import .ttl souborů, aby také uměla řádně importovat slovníky se všemi typy elementů - neměl by to být časově náročný problém.

Read-only slovníky jsem pochopil tak, že uživatel nemůže měnit v komponentě dostupné stereotypy,  - proto jsem přidal do komponenty startovací argument lockConfig, který tomu zabrání.

Mám problém s importem VS-GOV slovníku (viz trello - https://trello.com/c/K82QNihm/21-vytvo%C5%99it-instanci-ontouml-s-zsgov-konstrukty) - nevím, jestli je to ve scopu tohoto issue, jelikož se jedná o konkrétní problém.

**Comment by bindetad** [comment]
Elementy se importují podle definované JSON struktury v b693b610b8797c4d349f5b25b63a3a8d040eb8b8. To, jak jsou importovány, je popsáno v #7.

**Comment by blcham** [comment]
"Konfigurace je v podobě JSON souboru, který bude umístěn na nějaké veřejně dostupné IRI. Default si bude ukazovat na defaultní konfigurační IRI a uživatel si to může změnit."

Can i see this default configuration from the application ? Can I change the IRI somewhere in the application ?

**Comment by bindetad** [comment]
You can change it in a [locally deployed version](https://github.com/opendata-mvcr/ontoGrapher/wiki/Running-ontoGrapher-locally). The IRI of the vocabulary JSON file is located in [defaults->defaultVocabularies](https://github.com/opendata-mvcr/ontoGrapher/wiki/Running-ontoGrapher-locally). The structure of the JSON is described [on the wiki](https://github.com/opendata-mvcr/ontoGrapher/wiki/Vocabulary-JSON), or you can consult [the JSON](https://github.com/opendata-mvcr/ontoGrapher/blob/master/src/config/Vocabularies.json) that is fetched in the default settings.

**Comment by blcham** [comment]
> Default si bude ukazovat na defaultní konfigurační IRI a uživatel si to může změnit.
From the description, I was expecting that the user can change it in UI. Since it was ambiguous, I will rather put it into separate ticket.

I consider this issue to be closed.

**Comment by blcham** [comment]
Changing vocabulary configuration from UI should be discussed, see #13.
