### ISSUE TITLE
Adding a relator type to a diagram adds also hidden relator types

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#100]
I added an object type "Časový okamžik" to a diagram. It added also relator types with the object type "Věc" which was already on the canvas:

![image](https://user-images.githubusercontent.com/4235208/92699911-74280580-f34e-11ea-8519-dc18cd0ec129.png)

I do not like adding all the relator types, but OK if there was a requirement for this (was there?).

I do not want the relator types so I hide them:

![image](https://user-images.githubusercontent.com/4235208/92700565-42636e80-f34f-11ea-9005-4128c141a12d.png)

Then I need a relator type "má nástup" on the canvas between "Časový okamžik" and "Pracovní místo". When I add it on the canvas, all hidden relator types are shown. This is an incorrect behavior.

Moreover, the shown relator types are still marked as hidden on the left.

![image](https://user-images.githubusercontent.com/4235208/92700450-1cd66500-f34f-11ea-823d-d5818d40bf2f.png)

**Comment by bindetad** [comment]
As of 420c2db, this issue seems to be resolved.

**Comment by psiotwo** [comment]
I wasn't able to reproduce the incorrect behaviour, but @martinnec would be better to check.

**Comment by martinnec** [comment]
I can still reproduce it. Lets have a call and I will show.

**Comment by bindetad** [comment]
I was finally able to reproduce the issue and made a fix in e894a89f6be3c1a63674501d817d8c0be6b1edb8.

**Comment by psiotwo** [comment]
Again, tried and wasn't able to reproduce the incorrect behaviour - @martinnec please check.
