### ISSUE TITLE
Cannot see newly TermIt-created term in OntoGrapher

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#104]
A term "Eviduje skvěle' created in TermIt does persist in GraphDB:
![image](https://user-images.githubusercontent.com/1140626/93484315-0f4a4d80-f902-11ea-9672-5b4ab8e8aacd.png)

But I cannot see it in Ontographer:
![image](https://user-images.githubusercontent.com/1140626/93484170-e45ff980-f901-11ea-98c8-64486d03b858.png)

Workspace:https://mission-control.netlify.app/workspaces/instance1771937413

**Comment by bindetad** [comment]
As of e894a89f6be3c1a63674501d817d8c0be6b1edb8 I can see terms created in Termit.

**Comment by psiotwo** [comment]
Works OK, closing.
