### ISSUE TITLE
Two workspaces influence each other

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#106]
Workspace https://mission-control.netlify.app/workspaces/instance-1399010047 (GSGoV - témata dizertačních prací)

I have this diagram in ontographer:

![image](https://user-images.githubusercontent.com/4235208/93664176-45f0a700-fa6d-11ea-9e45-400c8a15735f.png)

When I edit it in ontographer, leave it, return to it, everything is OK.

Then I go to another workspace https://mission-control.netlify.app/workspaces/instance-662374584 (GSGoV - zaměstnání)

I have this diagram in ontographer:

![image](https://user-images.githubusercontent.com/4235208/93664228-85b78e80-fa6d-11ea-920b-0228d919646e.png)

I edit it:
Object class "Pracoviště" from Generický slovní pro zaměstnání:

![image](https://user-images.githubusercontent.com/4235208/93664279-c911fd00-fa6d-11ea-82ad-bb63778445c5.png)

I drag it to the diagram - some relations to other elements appear.

Now I get back to the first workspace and open it in ontographer.

What I see is the original diagram but without "Pracoviště"

![image](https://user-images.githubusercontent.com/4235208/93664304-0c6c6b80-fa6e-11ea-9333-f3bc6167938f.png)

And vice versa, when I work in ontographer with something in the second WS what is also in the first workspace, it disappears from the diagram in the first workspace.

**Comment by bindetad** [comment]
As of e894a89 the update of the configuration of workspaces should prevent unwanted changes to other workspaces.

**Comment by psiotwo** [comment]
Checked, looks good.
