### ISSUE TITLE
Read-only vocabularies still allow editing

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#109]
Having a workspace where all vocabularies are R/O, e.g. https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-662374584

I can still add a new link, even if no vocabulary is R/W.
 Also, I can drag a node to a diagram.

I should not be able to change the model or diagram when the vocabulary is R/O

**Comment by bindetad** [comment]
I understand the general issue, but I'm not clear on why the R/O concepts shouldn't be placed on diagrams. The model isn't changed by this, and without diagram changes, any visual arrangement of R/O terms and their relationships would be lost on workspace reload. Moreover, diagram representation isn't present at all until ontoGrapher creates it. Maybe I'm not understanding you correctly.

**Comment by psiotwo** [comment]
Allowing to make changes in diagram on top of a R/O vocabulary - you are right.

Yet, this highlights the problem @karelklima was refering to - that diagrams are used both for modeling and visualization.

So this ticket only relates to creation of edges.
