### ISSUE TITLE
Delete selection in Relationship overview popup does nothing

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ontoGrapher#11]
How to reporduce :
1) click Settings/Relationships... 
2) select on any existing relationship
3) click "Delete selection"

Relationship is not deleted and there is no error in console.

**Comment by bindetad** [comment]
Should be fixed in 5343096fdbafaeebbeb9a4e34a3e6bde80ee1626, please confirm.

**Comment by blcham** [comment]
checked.

**Comment by blcham** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontroGrapher #2](https://trello.com/c/jjYcBXyE/65-pr%C3%A1ce-na-issues-v-ontrographer-2)
