### ISSUE TITLE
Cannot hide elements

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#115]
Working in workspace 
https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1269492277

When trying to hide an element from the diagram (Vyhlášený akt), I end up with 
![image](https://user-images.githubusercontent.com/1140626/95680850-abebcc80-0bdc-11eb-9f7f-8c93bf3a0817.png)

**Comment by bindetad** [comment]
In fca1208, I was not able to reproduce the issue using your workspace.

**Comment by psiotwo** [comment]
Cannot reproduce, so OK.
