### ISSUE TITLE
Visualize information which vocabulary a node/edge belongs to

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#116]
Having a workspace with many vocabularies, it is difficult to understand which node/edge belongs to which vocabulary in a diagram. 

The goal is to make it clear to distinguish nodes/edges from different vocabularies - e.g. by colors, or icons.

**Comment by bindetad** [comment]
This enhancement has been implemented in e44bd1e - the nodes and vocabularies (in the left panel) are now colored appropriately.

**Comment by psiotwo** [comment]
Looks good - I like the minimalistic coloring bar. Not sure whether it is maybe not too minimalistic :-) Let's discuss with others and see.

**Comment by bindetad** [comment]
In 28081f3, I changed the visualization to be the whole background of the concept and presented various options that can be chosen from - see the newly created View submenu on the menu bar.

**Comment by psiotwo** [comment]
Looks great. Would be great if some color scheme is chosen by default - my favorite is the "light pastel".

**Comment by bindetad** [comment]
In 2c9971b,
* the default color scheme is changed to "light pastel".
* the selected color scheme is saved per workspace.

**Comment by psiotwo** [comment]
Tested,OK.
