### ISSUE TITLE
Wrong cardinality on compact view

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#117]
FULL: (1:*, 1:1)
![image](https://user-images.githubusercontent.com/1140626/95688915-b3779980-0c0d-11eb-85b1-17b27a9e42c3.png)

COMPACT: (1:1)
![image](https://user-images.githubusercontent.com/1140626/95688901-a490e700-0c0d-11eb-8b1b-7245eb7b0acf.png)

But should be 1:* in COMPACT

**Comment by bindetad** [comment]
This issue is fixed in fca1208.

**Comment by psiotwo** [comment]
Checked, OK.
