### ISSUE TITLE
Wrong cardinality rendering

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#118]
When I choose cardinality for a link and then reconsider my decision and pick another cardinality, it happens that the original cardinality is still depicted overlaying the former:

![image](https://user-images.githubusercontent.com/1140626/95689199-744a4800-0c0f-11eb-827a-e21da9184067.png)

**Comment by bindetad** [comment]
This issue is fixed in fca1208.

**Comment by psiotwo** [comment]
Cannot reproduce any more, so OK.
