### ISSUE TITLE
Provide tooltips for panel elements

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ontoGrapher#12]
As a user I would hardly undestand 4 tabs within "component's element panel". For example "P&M", "D" means "packages with models", "diagrams" which is very unintutive. Although not very nice for mobile version of the application, tooltip would help there.

**Comment by bindetad** [comment]
I have created tooltips in 5343096fdbafaeebbeb9a4e34a3e6bde80ee1626. What do you think?

**Comment by blcham** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontroGrapher #2](https://trello.com/c/jjYcBXyE/65-pr%C3%A1ce-na-issues-v-ontrographer-2)

**Comment by blcham** [comment]
looks good :).
