### ISSUE TITLE
Deleting elements does not work when they are in the diagram

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#121]
Working in https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1269492277

1) I created a new element (label 'X' in the V-SGoV voc)
2) I immediately tried to delete it in the right panel (without hiding it first)
3) I ended up with the following screen
![image](https://user-images.githubusercontent.com/1140626/95984731-ee531a80-0e23-11eb-89b0-d53ac0b02947.png)

**Comment by bindetad** [comment]
This issue is resolved in e44bd1e.

**Comment by psiotwo** [comment]
I am still able to reproduce it as follows:
- created node A
- created node B
- created relationship R between A and B through má-vztažený-prvek-1 and má-vztažený-prvek-2

Upon hiding R, I get the following screen:
![image](https://user-images.githubusercontent.com/1140626/96646519-8bceb280-132c-11eb-9626-6eb02614e3bb.png)

**Comment by bindetad** [comment]
In 28081f3, I can no longer reproduce the issue.

**Comment by psiotwo** [comment]
Tested. OK
