### ISSUE TITLE
Fix concept serialization

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#122]
Currently, a new/edited concept is not serialized properly, as it is not in the hierarchy:
- for newly created concepts, the triple <current-glossary> skos:hasTopConcept <new-concept> should be added to the vocabulary
- for edited concepts, the above triple is left intact (preserved if it exists, not created otherwise)

**Comment by bindetad** [comment]
This issue is resolved in e44bd1e.

**Comment by psiotwo** [comment]
Checked, OK.
