### ISSUE TITLE
Deleting nodes still leaves some triples referencing the deleted subject

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#124]
Running on kodi-uloziste-dev:

```
SELECT *  { 
    GRAPH ?g {
	  ?s ?p <https://slovník.gov.cz/generický/právo/pojem/Právní-předpis>  .
    }
}
```

I am getting results in several named graphs:

1 | d-sgov-pracovní-prostor-pojem:kontext-sledování-změn/instance1607087389 | a-popis-dat:pojem/úprava-entity/instance-1295007543 | a-popis-dat:pojem/má-původní-hodnotu
-- | -- | -- | --
2 | d-sgov-pracovní-prostor-pojem:slovníkový-kontext/instance593480509 | _:node6633 | owl:someValuesFrom
3 | d-sgov-pracovní-prostor-pojem:slovníkový-kontext/instance593480509 | _:node6634 | owl:allValuesFrom
4 | http://onto.fel.cvut.cz/ontologies/application/ontoGrapher | http://onto.fel.cvut.cz/ontologies/application/ontoGrapher-9e7259d7-8b5d-412c-bd92-b3e700d3baec | og:target
5 | http://onto.fel.cvut.cz/ontologies/application/ontoGrapher | http://onto.fel.cvut.cz/ontologies/application/ontoGrapher-4f8fe3e5-e799-4918-a95d-98c729445a95 | og:target

But running 
```
SELECT *  { 
    GRAPH ?g {
	 <https://slovník.gov.cz/generický/právo/pojem/Právní-předpis> ?p ?o .
    }
}
```

gives nothing - i.e. the concept has been deleted. Yet some related triples are still in after the deletion.

**Comment by bindetad** [comment]
This issue is resolved in e44bd1e9a0c617a49add722c301f48583edf78ca.

**Comment by psiotwo** [comment]
Having in diagram A (Typ Objektu) - R (Typ Vztahu) - B (Typ Objektu), hiding A and R and then deleting A and R in the  tree on the left, I end up with
- correct glossary - containing only B
- dirty model - it contains additional empty triples

```[] a owl:Restriction;
  owl:onProperty z-sgov-pojem:má-vztažený-prvek-2 .

[] a owl:Restriction;
  owl:onProperty z-sgov-pojem:má-vztažený-prvek-2 .

[] a owl:Restriction;
  owl:onProperty z-sgov-pojem:má-vztažený-prvek-1;
  owl:someValuesFrom :B .

[] a owl:Restriction;
  owl:allValuesFrom :B;
  owl:onProperty z-sgov-pojem:má-vztažený-prvek-1 .```

**Comment by bindetad** [comment]
In 28081f3, from now on, deleting will also delete these triples mentioned above.

**Comment by psiotwo** [comment]
Tested. OK.
