### ISSUE TITLE
Cardinalities are not exported for 'Typ vlastnosti'

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#125]
For 'Typ vlastnosti' stereotyped nodes, I can only see someValuesForm/allValuesFrom triples and not cardinalities (although filled in) in the exported TTL.

**Comment by bindetad** [comment]
In 28081f3, these restrictions are now exported.

**Comment by psiotwo** [comment]
Still cannot see cardinalities in the export:
Publishing
https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1042022389, where R has cardinalities

results in PR  https://github.com/opendata-mvcr/ssp/pull/162/files (no cardinalities for R)

**Comment by bindetad** [comment]
In d233aab, these cardinalities are now exported (my apologies, I thought that they should only be exported for "typ vlastnosti" concepts).

**Comment by psiotwo** [comment]
![image](https://user-images.githubusercontent.com/1140626/97896300-2ec3fb00-1d35-11eb-945c-fe700b639a4f.png)
results in 

https://github.com/opendata-mvcr/ssp/blob/9321335d478d80368d010e9e5126f7fb52b82817/content/l-sgov/l-sgov-sb%C3%ADrka-131-2000/l-sgov-sb%C3%ADrka-131-2000-model.ttl

This is strange, as the diagram claims multiple min cardinalities >=1, but in the export I can see just one.

**Comment by bindetad** [comment]
This is fixed in efc85fc.

**Comment by psiotwo** [comment]
Tested. OK
