### ISSUE TITLE
Visualization of different content types in diagram by different shapes

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#126]
- node without stereotype - rectangle with gray text and dashed border (to show that it is incomplete)
- "Object type" shown as rectangle
- "Relationship type" shown as diamond
- "Trope Type" shown as skewed rectangle?
- "Event type" shown as ellipse ?

**Comment by psiotwo** [comment]
@opendata-mvcr/c5-devs ^ please comment

**Comment by psiotwo** [comment]
![image](https://user-images.githubusercontent.com/1140626/98051238-b728c580-1e33-11eb-9e1a-485b0e79e641.png)

**Comment by psiotwo** [comment]
@opendata-mvcr/c5-devs ^ please comment

**Comment by blcham** [comment]
"Object type", "Relationship type" and "Trope type" is intuitive as the chosen visualization is the convention in ER diagrams. 
https://conceptdraw.com/a977c4/preview

The only missing visualization is for "Event type". Events and relationships are closely related in UFO so I would choose probably a similar shape?! How about a hexagon?

**Comment by psiotwo** [comment]
Event type will be trapezoid-shaped.

**Comment by bindetad** [comment]
In 8fd49e7, type concepts have the aforementioned shapes (when the labels are long, the shapes look off in my opinion - perhaps label line breaks are in order?)

**Comment by psiotwo** [comment]
Shapes for 'typ vlastnosti' and 'typ vztahu' seem to be accidentally switched.

Re: labels - line breaks sounds reasonable.

**Comment by psiotwo** [comment]
fixed. works.
