### ISSUE TITLE
Expand all related terms

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#127]
It shall be possible to expand all related terms (i.e. specializations and generalizations, properties, relations and related objects) for every term. In connections, there is Explode all button, but it does not always work (mostly if relation points to the other vocabulary). Try generalization between "Právnická osoba" and "Gestor" in "eSbírka" model.

**Comment by MichalMed** [comment]
It is only possible to view the relation by putting both terms into the canvas and THEN exploding relations.

**Comment by bindetad** [comment]
In 35522b5, I can't find any relations that can't be expanded (I tried various examples from different vocabularies). If you can find a particular example that does not work, please let me know.

**Comment by MichalMed** [comment]
I have described it in the example in the first comment, but I have then deleted the generalization, because it was no more valid. Now it does not appear, so I'm closing
