### ISSUE TITLE
Moving relation arrows

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#128]
Moving arrows is not done very useful. In most cases it is easier to remove arrow and create it again than trying to reshape it. Biggest problem is in moving already created moving points and moving the point where is arrow attached to the term.

**Comment by psiotwo** [comment]
I don't understand this issue. Aren't edges moved by moving the source/target nodes? 

Once multiselection is supported (#114) moving both source and target nodes should result in moving the edge.

**Comment by MichalMed** [comment]
You can create breaking ponts on the edge

**Comment by MichalMed** [comment]
the problem is that if you are trying to move it alone, you often by mistake click delete or info. That shall not happen. One of the buttons is often covering the breaking point.
![Screenshot from 2020-10-29 18-36-33](https://user-images.githubusercontent.com/3779672/97610994-e3001180-1a15-11eb-865a-b0a4015142fd.png)

**Comment by psiotwo** [comment]
- allow selecting the whole edge (info button not needed any more)
- show delete button only when the edge is selected

Related to #131

**Comment by bindetad** [comment]
In 2c9971b (the 9th of November version), relationships can be selected by clicking anywhere on the relationship itself. This means that:
* The deletion button is only shown upon selection (in addition, it is also now located closer to the domain concept to hopefully get it out of the way).
* The info button no longer exists.
* Modifying the relationship's shape is also only possible after selecting the relationship.

**Comment by MichalMed** [comment]
I think that this issue and #131 are so related that most comments are regarding both of them. This issue will be solved by solving #131 , so I am closing this one and adding comments to #131 .
