### ISSUE TITLE
Putting more terms into canvas at once

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#129]
It is very annoying to put higher number of terms into the canvas, because it must be done one by one. I suggest to allow putting all terms at once AND selecting various number from the list (by holding Shift) and move them all at once into the canvas.

**Comment by psiotwo** [comment]
We can have something like "Select/Deselect all" switch for each vocabulary. Then you can still manually revise the selection. Upon d'n'd all the selected concepts will be moved to the canvas.

**Comment by MichalMed** [comment]
Select/deselect all is a nice start, but it have to be possible to manually revise.

**Comment by psiotwo** [comment]
- select/deselect
- actions - add to canvas (multiple actions expected)

**Comment by psiotwo** [comment]
This functionality should be in place for the selection of terms as designed in https://github.com/opendata-mvcr/ontoGrapher/issues/146.

**Comment by bindetad** [comment]
In 8fd49e7, you can select individual terms, terms by type, or whole vocabularies and place them on the canvas at once (you select them with the provided checkbox and then drag them onto the canvas as before).

**Comment by psiotwo** [comment]
tested, works. See #149 as a follow-up issue.
