### ISSUE TITLE
Relations between terms are not always shown

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#130]
There is a bug, that in some cases, relation between two terms is not shown even if both of them are put into the canvas. The It happens usually for terms from different vocabularies, but better check it.

**Comment by bindetad** [comment]
In 35522b5, I checked various relations from same and different vocabularies and could not find an issue - if you find any particular example, please let me know.

**Comment by MichalMed** [comment]
It looks like those that did not work work now.
