### ISSUE TITLE
Select relation by clicking on it

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#131]
Now it is possible to select a relation arrow by slicking on little (i) on the edge. It shall be possible to select it by clicking anywhere on the edge.

**Comment by bindetad** [comment]
In 2c9971b (the 9th of November version), relationships can be selected by clicking anywhere on the relationship itself (for more information, see [my comment](https://github.com/opendata-mvcr/ontoGrapher/issues/128#issuecomment-724032802) in #131).

**Comment by MichalMed** [comment]
It works as intended, but there is a bug:
+ If I select and edge and then any node, edge is no more selected, but acts as it is (you can move breakpoints and add new ones and you can delete the edge).
There is also a thing, not really sure if intended, that if edge is not selected, I can move the whole edge (meaning all breakpoints at once). Is this intended or not?

**Comment by bindetad** [comment]
In 1905177 (currently deployed), the bug you mentioned has been resolved. The relationship moving is intended so that you can quickly (i.e. in a way that does not require clicking, only dragging) move the relationship.
