### ISSUE TITLE
Support Esc keyboard button

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#132]
It happens quite often that by double-clicking something I also click to the empty place in canvas, opening new concept dialogue. It shall be possible to close it by Esc, not only by clicking cancel.

**Comment by psiotwo** [comment]
Not sure about this one. It is not a dialog, but rather a side panel ...

**Comment by MichalMed** [comment]
This one: ![Screenshot from 2020-10-29 18-41-43](https://user-images.githubusercontent.com/3779672/97611427-79343780-1a16-11eb-920a-5c02093c1fe5.png)

**Comment by bindetad** [comment]
In 2c9971b (the 9th of November version), this dialogue responds to the Escape key.

**Comment by MichalMed** [comment]
Supermegagreatappriciate

**Comment by MichalMed** [comment]
Supermegagreatappriciate
