### ISSUE TITLE
Switching from compact to full view does not keep layout

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#133]
In compact view, all properties are shown as attributes (in a UML meaning) and relation are shown as edge labels. After editing compact layout and switching to full, all properties and relation boxes are kept in a place they were before the changes. It shall be much better if relations were moved in the middle of the labeled edge in compact view and properties in some reasonable area around the object. This would significantly enhance the clarity of the model.

**Comment by bindetad** [comment]
This is implemented in 8fd49e7 (attributes and relationships types are moved on compact view position changes).

**Comment by MichalMed** [comment]
Ok, it looks like this problem is solved, but other is raised. I'm closing this one and opening a new one #155
