### ISSUE TITLE
Relations with same domain and range looks weird in compact view

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#135]
Relations with same domain and range looks weird in compact view :)

**Comment by bindetad** [comment]
In 2c9971b (the 9th of November version), this seems to be resolved.

**Comment by MichalMed** [comment]
Done. But if I switch to compact, move the edge a little and then switch back to full, it still looks like before (which is probably good), but then, when I switch back to compact, changes vanished (which is probably bad). This is minor issue, please just check if it is easy to solve, otherwise I'll close it.

**Comment by bindetad** [comment]
In 1905177 (currently deployed), this should be fixed - in general, shapes of "compact" relationships should be preserved from now on (maybe you will need to redo the shapes of existing "compact" relationships, but you shouldn't have to delete and redo them whole).
