### ISSUE TITLE
Support altlabels

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#136]
Some labels are really not very practical (e.g. "má citaci označení fragmentu znění právního aktu"). It would be practical to use altLabels ("má citaci") to be shown in the diagram.

**Comment by psiotwo** [comment]
We would need to decide when and how which label to chose (single pref + multiple alts). But makes sense. Ontograph user might pick one for each link - having prefLabel default.

**Comment by MichalMed** [comment]
I am for altLabel as default more :) Just because it is usually much shorter and may be duplicate with other concepts, mainly in the case of relators.

**Comment by psiotwo** [comment]
Yeah, but they might be more altLabels as well.

**Comment by psiotwo** [comment]
- allow adding/editing Altlabels in the right panel.
- disable editing preflabels

**Comment by bindetad** [comment]
Question about the styling - should the large header at the top be the selected display name or the prefLabel? This is how it looks now. I appreciate any feedback.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/56399637/100455503-18545980-30bf-11eb-9b4c-d3ff12d443f5.gif)

**Comment by psiotwo** [comment]
I am not sure, how to use the yellow label icon to change the "display label" - it should not switch between different languages  I feel that having rather a global switch ("Use display labels", checked by default) would be appropriate. (And the "content language" should be set globally in the end as well, but this needs some thinking how to combine it with the app language).

**Comment by psiotwo** [comment]
Also, it seems to me that the "display label" icon is on the wrong label
![image](https://user-images.githubusercontent.com/1140626/100523008-4e700700-31ad-11eb-9593-24c0517a02c9.png)

**Comment by MichalMed** [comment]
I disagree with Petr about the global button only. You may choose for different terms for different labels. This is also a workaround if you have more altLabels. By switching the "general swich" for displaying altLabels, you switch from prefLabel to first altLabel or from whatever it is to prefLabels.

**Comment by psiotwo** [comment]
IMO a global switch should be the correct way to switch between prefLabel/altLabel for display. And Yes, If you have more altLabels, then we might want to pick them individually. (Note that currently, the logic of the current implementation is wider. It allows switching display prefLabel/altLabel across languages).
