### ISSUE TITLE
Blank screen after node selection

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#140]
Workspace :
https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1703508316

After clicking on "Právnická osoba" from 111/2009 (which specializes another "Právnická osoba" from V-SGoV), I get a blank screen:
![image](https://user-images.githubusercontent.com/1140626/97555290-3c495000-19d8-11eb-8624-3288f3ceb6a3.png)

**Comment by bindetad** [comment]
In 28081f3, I can no longer reproduce the issue.

**Comment by psiotwo** [comment]
The diagram does not contain Pravnicka osoba any more.

But clicking on Pravni predpis
![image](https://user-images.githubusercontent.com/1140626/97839869-512d2880-1ce3-11eb-86a6-1028bad30681.png)

Results in a blank screen
![image](https://user-images.githubusercontent.com/1140626/97839901-5db18100-1ce3-11eb-9eb1-3bd2ad22788a.png)

Not sure whether these bugs are mutually related.

**Comment by bindetad** [comment]
In d233aab, this should be fixed.

**Comment by psiotwo** [comment]
tested. ok
