### ISSUE TITLE
Compact view makes nodes shrink in width

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#142]
When switched to compact view, the nodes get shrinked to the width of the label (although the stereotype is wider)

![image](https://user-images.githubusercontent.com/1140626/97871000-1c859500-1d14-11eb-83aa-eec14411fee7.png)

**Comment by bindetad** [comment]
This issue is fixed in efc85fc.

**Comment by psiotwo** [comment]
Tested. OK
