### ISSUE TITLE
Not all concepts exported in glossary have the link hasTopConcept

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#143]
Most concepts in glossaries are referenced by the hasTopConcept link of the respective glossary. But some don't and they also don't have skos:broader link to a concept which is referenced by the hasTopConcept link.

**Comment by bindetad** [comment]
I tried to find the culprit, but no luck so far: I don't manipulate skos:broader or skos:hasTopConcept triples, except as per #122 or concept deletion. I'll keep looking tomorrow.

**Comment by bindetad** [comment]
This seems like a simple issue to fix, but the main block is that perhaps I'm still not understanding it correctly. Looking at the code and doing various examples, here's the intended behavior regarding these predicates:
* &lt;glossary&gt; skos:hasTopConcept &lt;term&gt; is created for each new term. Other terms' skos:hasTopConcept triples are left untouched. Therefore, there is a possibility that some concepts won't have this triple.
* skos:broader triples are left untouched, regardless of whether there are any.
* The only exception is deletion of a concept, where all _&lt;term&gt; ?p ?o_'s and _?s ?p &lt;term&gt;_'s within the context are deleted.

During my tests, I kept an eye on the total count of these triples in the workspace. Aside from deleting (where the number of deleted triples looks to be correct), there were no changes. So it seems I either haven't spotted the trigger event that causes the issue or the intended behavior is wrong.

**Comment by psiotwo** [comment]
Underspecified. Closing.
