### ISSUE TITLE
Default relation cardinalities

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#144]
When I create a relation, e.g. "má vlastnost", "má vztažený prvek 1", cardinalities are empty. I would prefer to have some predefined, typical, cardinalities. E.g. for "má vlastnost", I would expect source cardinality "1..1" and target cardinality "0..1".

**Comment by psiotwo** [comment]
take default cardinality (e.g. from Z-SGoV: vlastnost subClassOf exactly 1 je-vlastností)
If no cardinality is specified, use 0..*
