### ISSUE TITLE
Partition the term selection list according to a stereotype

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#146]
The goal is to be able to see a list of terms with the specified stereotype (so that they can be (de)selected for addition to a diagram as a part of https://github.com/opendata-mvcr/ontoGrapher/issues/129)

**Comment by bindetad** [comment]
In 8fd49e7, terms are now sorted by "type" stereotypes.

**Comment by psiotwo** [comment]
lgtm.
