### ISSUE TITLE
Loading workspace crashes GraphDB

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#147]
When loading the workspace in OntoGrapher
https://mission-control.netlify.app/workspaces/instance-1411569177

everything works (OntoGrapher issues large amount of queries to GraphDB)

After making this change - https://github.com/opendata-mvcr/ssp/pull/177, deleting the workspace and recreating it with the same vocabularies makes the workspace unloadable in OntoGrapher. The amount of queries to GraphDB seems higher and GraphDB crashes on the lack of heap memory.

Might be an interaction with other services in GraphDB, but we were able to replicate this behaviour.

**Comment by psiotwo** [comment]
@MichalMed

**Comment by bindetad** [comment]
In a138dae, this seems to be resolved (in addition, initializing new workspaces should be much faster and less intensive on the DB). @MichalMed @psiotwo .

**Comment by psiotwo** [comment]
works for me.
