### ISSUE TITLE
UI for term actions in the vocabulary list

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#149]
The cross button and the selector checkbox for a term are very near to each other and will cause issues that users will accidentally delete terms when trying to select them and vice versa.

**Comment by bindetad** [comment]
In 35522b5, the checkboxes are on the left instead of the right. In addition, the user can shift-click on the whole left panel item to select it.

**Comment by psiotwo** [comment]
lgtm
