### ISSUE TITLE
Saving classes name is unintuitive

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ontoGrapher#15]
It is very unintuitive that you can rewrite name of multiple classes without saving them. 

Alternative solutions:
- warn user when class name is modified and focus is lost. User would have to confirm changes or he would be forced to loose changes.
- automatically save changes when name is changed  (I prefer that).

Demonstration of the issue, where I have 2 classes with names that were not saved :
![issue](https://user-images.githubusercontent.com/3962237/71785388-2b6dbf00-2fff-11ea-8818-fb7ecfc20639.gif)

**Comment by psiotwo** [comment]
fixed.
