### ISSUE TITLE
Redesign UI for managing stereotypes of a term

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#150]
Term stereotypes can be of two categories:
- content types - Object Type, Event Type, Relator Type, Aspect Type - these can be specialized in sublanguages (e.g. RUIAN types) - user can select one from this category
- OntoUML types - Kind, Role, ... - user can select one from this category

Design a UI for attaching and visualizing these two categories of types in a consistent way.

**Comment by psiotwo** [comment]
@opendata-mvcr/c5-devs ^ please comment

**Comment by bindetad** [comment]
In 35522b5f2ff8bb84beaa2749eee2d62c3efcc3f3, I separated the stereotype selector into two with each of the categories represented..

**Comment by psiotwo** [comment]
lgtm
