### ISSUE TITLE
Ontographer bug

### ISSUE THREAD

**Issue by JakubMalina** [opendata-mvcr/ontoGrapher#152]
Pokud u pojmu kliknu na šipku v levém horním rohu a poté kliknu doprostřed jiného pojmu, tak ontographer spadne.

**Comment by bindetad** [comment]
Mohl bys prosím napsat, jaké dva pojmy to byly v jakém pracovním prostoru? Mám pocit, že to souvisí s #157, ale chci si to potvrdit.

P.S. na Githubu komunikujeme v angličtině - jenom do budoucna :).

**Comment by bindetad** [comment]
Zavírám issue na základě domluvy s autorem. Pojmy, o které se jednalo, byly `Informační systém VS` ze 365/2000 a `NKOD` ze 106/1999. Pojmy již fungují, proto (prozatím) zavírám.
