### ISSUE TITLE
Cannot load diagrams when rdfs:subClassOf to external vocabularies added in TermIt

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#153]
1) https://ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666

2) I had there 2 diagrams. I could open them without any problems.

3) I went to TermIt and added rdfs:subClassOf or rdfs:subPropertyOf to the vocabulary items. E.g. for "Úroveň klasifikace":
![image](https://user-images.githubusercontent.com/4235208/99698220-d0b34980-2a90-11eb-915b-52ca5dcc334e.png)

4) When I now access https://ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666 , I got:

![image](https://user-images.githubusercontent.com/4235208/99698299-e7f23700-2a90-11eb-914e-6779999e7dac.png)

**Comment by bindetad** [comment]
Fixed in 3da33e2.

**Comment by martinnec** [comment]
Fixed.
