### ISSUE TITLE
Hidden relations reappear after opening the OG again

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#155]
I have created two tabs in Sbírka OG. In the fist tab are ONLY relations between terms from Sbírka. The second tab shall contain ONLY mapping to upper level vocabularies. This thing is, that most of the terms mapped are objects. I want to see here only objects, so automatically created relations between them were hidden. Unfortunately, if I get back to the WS and open the tab, relations are back.

**Comment by MichalMed** [comment]
actually it is enough to switch to other tab and back

**Comment by bindetad** [comment]
Reopened as the issue can still be reproduced.

**Comment by MichalMed** [comment]
solved by #184
