### ISSUE TITLE
Disallow creating terms with the same prefLabel

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#158]
If a term already with the same prefLabel already exists in the vocabulary, do not allow to create it and show an error to the user.

**Comment by psiotwo** [comment]
The validation works OK for Czech, but does not prevent from creating concepts with the same prefLabel in English.

**Comment by psiotwo** [comment]
I cannot press "Cancel" button when something is already filled in the Czech label. 
![image](https://user-images.githubusercontent.com/1140626/100523094-f259b280-31ad-11eb-9262-3148e319caef.png)

**Comment by psiotwo** [comment]
To be compliant with TermIt 

the prefLabel should be always referred as:
- Název/Label

the altLabel should be always referred as:
- Synonymum/Synonym

**Comment by bindetad** [comment]
All of the aforementioned complaints have been addressed in e789692 within #162.
