### ISSUE TITLE
stereotypes are sometimes not attached

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#159]
In a WS with quite a lot of terms (sbírka), saving takes extremely long. After creating a set of new terms and then attaching them a stereotype, sometimes the stereotype is not added (it takes a while, when nothing is happening and then drop down goes t odefault again).

**Comment by bindetad** [comment]
I haven't come across the issue in about a week - It looks similar to #164, which was resolved in #162. During my testing, creating and stereotyping new concepts rarely takes longer than a second per change (even in busy workspaces, such as Sbírka). The transaction used to be unnecessarily large, but that was resolved in #174, so it would seem that the biggest delay is communicating with the server. Is the issue resolved for you? If not, how long is the saving, exactly?
