### ISSUE TITLE
Diagrams do not preserve their state

### ISSUE THREAD

**Issue by blcham** [opendata-mvcr/ontoGrapher#16]
If I am changing from one diagram to the other one I loose its state.

The way to simulate it:
- create "diagram 1"
- create "diagram 2"
- drag&drop classes to diagram 2   (diagram 2 now contains some classes)
- switch to diagrams 
     - **BUG 1**: "Untitled" is selected
- switch to "diagram 1"
- switch back do "diagram 2"
     - **BUG 2**: Diagram 2 now does not contain any classes.

Demonstration:
![x webm](https://user-images.githubusercontent.com/3962237/71785791-22cbb780-3004-11ea-81ee-fbc08701e533.gif)

**Comment by psiotwo** [comment]
fixed.
