### ISSUE TITLE
The OntoUml types are not set correctly.

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#164]
Sometimes theOntoUml types are mismatched. After changing a type the previous is not deleted ... See
![image](https://user-images.githubusercontent.com/1140626/100659377-d80c0a00-3350-11eb-8538-664d3cc9be74.png)

**Comment by bindetad** [comment]
Was that on the main deploy (currently up to date with #162)? I noticed that issue as well and tried to fix it there. Try changing one of the types to something else and back again.

**Comment by psiotwo** [comment]
lgtm
