### ISSUE TITLE
Empty  fields should not be exported

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#169]
Currently, empty fields are exported as empty values. For example prefLabel@en. This also causes problems with validation because as a result the vocabulary contains two concepts with the same prefLabel (which is forbidden).

![image](https://user-images.githubusercontent.com/1140626/100782149-44980f00-340c-11eb-8b85-c11e89b6bf39.png)

**Comment by psiotwo** [comment]
Still reproducing this problem:
https://github.com/opendata-mvcr/ssp/pull/190/files

**Comment by bindetad** [comment]
Forgot to mention that in order to fix broken concepts, you have to alter something in the detail panel, e.g. the definition, stereotype, synonym, anything at all that results in a save. I tried this in a WS and it deleted the broken triples.

**Comment by psiotwo** [comment]
Ah I see. Now it works. Thanks.
