### ISSUE TITLE
Class properties represented as attributes

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#18]
Each term in our semantic vocabulary has properties such as term label or search index. In UML, terms are represented as UML classes. In ontoGrapher these properties are represented as attributes of these classes which is not correct. Having them as attributes means, that they are properties of instances of these classes. However, this is not true. They are properties of the terms. Therefore, they must be represented as properties of the classes. It must be possible to specify also the property value of a class.

In other words, instead of:

![image](https://user-images.githubusercontent.com/4235208/71809468-7542bd80-3070-11ea-8a3d-a19fa8d075a7.png)

There should be:

![image](https://user-images.githubusercontent.com/4235208/71809844-38c39180-3071-11ea-9d4c-ed50287aa863.png)

The list of properties can be seen in Modelio. Here is a sample snapshot:

![image](https://user-images.githubusercontent.com/4235208/71809941-74f6f200-3071-11ea-8248-83edf124b2f7.png)

The properties should be be shown in the UML diagram. Only on the detail of the class after selecting the class.

**Comment by bindetad** [comment]
Should be fixed as of 26941f484858f1b980c591f2abfb2ae3f8e40ce0.

**Comment by psiotwo** [comment]
checked.
