### ISSUE TITLE
Diagram layout is not kept

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#181]
I can see the diagram in V-SGoV číselníky WS as : 
![image](https://user-images.githubusercontent.com/1140626/101635146-dcf44c00-3a29-11eb-9944-10a82cc1da1d.png)

However when the WS is opened from another machine, it renders as:
![image](https://user-images.githubusercontent.com/1140626/101635187-e8477780-3a29-11eb-9d11-80fa0f5764fd.png)

**Comment by MichalMed** [comment]
duplicate to #178
