### ISSUE TITLE
Almost all specializations of types have disappeared from canvas

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#186]
In tab Číselník, almost all specializations (leaves on the outer rim) and the top level term (in the middle) have disappeared (i.e. went invisible). This cannot happen.

**Comment by bindetad** [comment]
Does this resemble what it's supposed to look like? If so, it is resolved in dea7ab17 within PR #184.
![Snímek obrazovky 2020-12-12 215457](https://user-images.githubusercontent.com/56399637/101994747-f5cc5e00-3cc4-11eb-9af7-cd977ba70bc9.png)
![Snímek obrazovky 2020-12-12 215511](https://user-images.githubusercontent.com/56399637/101994748-f6fd8b00-3cc4-11eb-8bb3-bbf185b481ac.png)
