### ISSUE TITLE
Přidávání popisu stereotypu maže identifikátor

### ISSUE THREAD

**Issue by ledsoft** [opendata-mvcr/ontoGrapher#2]
Při ručním vytváření nového stereotypu vstup do políčka "Description" přemaže obsah políčka "IRI Identifier".

**Reprodukce**:
1. Settings -> Stereotypes...
2. Create new stereotypes, vybraný tab "Manually"
3. Vyplnit název a identifikátor
4. Při psaní popisu se přemaže identifikátor a v políčku pro popis se nic nezobrazuje

**Comment by bindetad** [comment]
Issue je v 544c4ea605c7f56fc5bbbba42b683a20a53da11e vyřešen, uzavírám.

**Comment by martinnec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontoGrapher #1](https://trello.com/c/RCIYuzZP/22-pr%C3%A1ce-na-issues-v-ontographer-1)

**Comment by blcham** [comment]
checked.
