### ISSUE TITLE
Incorrect visualization of UML association 

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#20]
UML associations are visualized as UML specializations:

![image](https://user-images.githubusercontent.com/4235208/71810566-f7cc7c80-3072-11ea-8546-e608a828bf86.png)

See the following figure as an example of correct visualization of associations:

![image](https://user-images.githubusercontent.com/4235208/71810717-53970580-3073-11ea-9b99-7868edbd82e1.png)

**Comment by psiotwo** [comment]
fixed.
