### ISSUE TITLE
Division on exploding connections to and from is contraproductive in visualization

### ISSUE THREAD

**Issue by MichalMed** [opendata-mvcr/ontoGrapher#207]
During recreation of Sbírka layout, I want to have visualized all tropes (connections coming from node) and all  relators (connections coming to the node) at once. I can do it only separately and then they partially overlap. Two solutions:
* add explode all connections button,
* while exploding connections from the node that is already partially exploded, take into account position of already existing connections

**Comment by psiotwo** [comment]
- button to explode all connections
- checkboxes to 1) (de)select all connections, 2) (de)select individual connections, and the d'n'd
