### ISSUE TITLE
Visualize which component detail is shown

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#21]
When clicking 'i' on a node/link in a diagram, the node/link details are shown in a panel on the right.
However the diagram node/link itself is not highlighted, so the user is not sure after a while which node/link is he editing.

A/C: 
- highlight the node/link as it was before (blue border) whenever its details are shown in the panel

**Comment by bindetad** [comment]
Implemented as of 26941f484858f1b980c591f2abfb2ae3f8e40ce0, but with an orange border instead of a blue one. If necessary, I can change it.

**Comment by psiotwo** [comment]
I am able to see the border correctly. 

A problem appears when I select different nodes/links in sequence. At some point I got the following state:

![image](https://user-images.githubusercontent.com/1140626/77208487-33b4a100-6afc-11ea-93e4-35e90313a23c.png)

**Comment by bindetad** [comment]
Should be fixed as of 8c50b84f79428ae2292d49d18b99d7a4616fdb70.

**Comment by psiotwo** [comment]
checked.
