### ISSUE TITLE
Mouse buttons ergonomics

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#211]
Current behavior:

Left mouse click = selecting nodes
Middle mouse hold and move = move diagram
Middle wheel = zoom
Right mouse click = new element

I need to move diagrams often but doing this with the middle button (which is a wheel on most mouses) is an ergonomy problem for me. Moreover, there is no middle button on most keyboards.

I propose:

Left mouse click (or double click?) = new element
Left mouse hold and move = selecting nodes
Middle wheel = zoom
Right mouse hold and move = move diagram

**Comment by psiotwo** [comment]
currently also:
- shift+left mouse = move

**Comment by psiotwo** [comment]
maybe just hint box

**Comment by psiotwo** [comment]
@bindetad confirmed that the current behaviour is consistent with Enterprise Architect's. So this ticket would be about providing a hint box.

I propose to reuse the existing 'help' dialog.

**Comment by martinnec** [comment]
I agree.
