### ISSUE TITLE
zobrazuje se špatný název pojmu

### ISSUE THREAD

**Issue by RadkaDomanska** [opendata-mvcr/ontoGrapher#219]
V ontographeru vidím v levém menu pojem "údaj" a jakmile ho přetáhnu do workspace zobrazí se jako "neveřejný údaj", nikoli jako "údaj"

**Comment by psiotwo** [comment]
To pravděpodobně bylo způsobeno tím, že levý panel nezobrazoval alternativní názvy pojmů. To již v #136 zobrazuje.
