### ISSUE TITLE
Distinguish stereotypes visualization from instance name

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#22]
Whenever 'Typ objektu' is dragged into a diagram, the following node is shown

![image](https://user-images.githubusercontent.com/1140626/76971036-f51cbc00-692c-11ea-86d7-2cbe3b6bae5a.png)

The meaning is that 'Untitled' is the name of the newly created class, and 'Typ objektu' is the UFO type the newly created class is instance of. 

A/C:
- display the type as a UML stereotype
![image](https://user-images.githubusercontent.com/1140626/76972458-ea632680-692e-11ea-8c27-c91a31639835.png)

**Comment by bindetad** [comment]
Implemented as of 26941f484858f1b980c591f2abfb2ae3f8e40ce0.

**Comment by psiotwo** [comment]
checked.

**Comment by bindetad** [comment]
Understood. I have changed that in 8c50b84f79428ae2292d49d18b99d7a4616fdb70.

**Comment by psiotwo** [comment]
checked.
