### ISSUE TITLE
Trim labels

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#225]
When creating a new concept and setting a prefLabel it is not trimmed, ending up e.g. in "perso**n     "**@cs.

Perform trimming for textual inputs on create/edit (labels, descriptions)

**Comment by karelklima** [comment]
Maybe we should think through how do we want to sanitize used input. Should we maybe filter out special characters as well? What about double spaces? Some standardization would be good, but at the same time we probably shouldn't put too many restrictions in place.

**Comment by psiotwo** [comment]
> Maybe we should think through how do we want to sanitize used input. Should we maybe filter out special characters as well? What about double spaces? Some standardization would be good, but at the same time we probably shouldn't put too many restrictions in place.

Agree, but on the other hand it might be tricky to define general rules for that (even the labels contain slashes/percents, etc. time-to-time).

**Comment by psiotwo** [comment]
Fixed.
