### ISSUE TITLE
Merge models into packages

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#23]
The currently edited project has two notions:
- models
- packages

However, 'model' is a read-only 'package' and should be visualized in the same component (just as read only. 

A/C:
- remove 'model' tab in the UI
- visualize the current content of the 'model' tab in the 'package' tab. E.g. VSGoV package will instances of VSGoV vocabulary that are currently in the 'model' tab. 
- disallow moving (and d'n'd) imported (model) instances out of the model package(e.g. out of the VSGoV package).

**Comment by bindetad** [comment]
This is implemented as of 26941f484858f1b980c591f2abfb2ae3f8e40ce0. Models are marked by the same symbol as that which previously marked the Models tab that existed before. They can't be moved.

**Comment by psiotwo** [comment]
Do we need the 'Models' node? Maybe making all models roots (e.g. VSGoV in the example) would be fine?
![image](https://user-images.githubusercontent.com/1140626/77208665-9dcd4600-6afc-11ea-90d6-c82900fa64b8.png)

**Comment by bindetad** [comment]
We don't, I just thought at the time that that would possibly be more intuitive. Since there probably won't be large amount of models, though, I have removed this central folder and moved all model folders to the root as of 8c50b84f79428ae2292d49d18b99d7a4616fdb70.

**Comment by psiotwo** [comment]
checked.
