### ISSUE TITLE
Renaming diagram works strange

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#24]
**Scenario:**
- click 'pencil symbol' to rename a diagram. 
- a dialog appears and I can change the name.
- **Once I hit 'enter', the dialog closes, the app redirects to the 'models' tab. After navigating back to the 'diagrams' tab, the diagram still contains the original name (before change)**
- click 'pencil symbol' again to rename a diagram
- a dialog appears and I can change the name
**- now hitting enter does not close the dialog at all**

**Comment by bindetad** [comment]
Should be fixed as of 26941f484858f1b980c591f2abfb2ae3f8e40ce0: from now on, Enter can't be used to send forms.

**Comment by psiotwo** [comment]
checked.
