### ISSUE TITLE
Changing relationships type does not work

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#25]
- create a two nodes and a link between them (e.g. má vztažený prvek)
- click 'i' to get into 'Relationship details'
- the last drop down shows the type of relationship. The list of possible types appears, but upon selection of another type (e.g. "je vlastností") the dropdown value is the same and does not change (i.e. it still shows "má vlastnost")

As a result, I cannot change the type of relationship.

**Comment by bindetad** [comment]
Should be fixed as of 26941f484858f1b980c591f2abfb2ae3f8e40ce0.

**Comment by psiotwo** [comment]
checked.
