### ISSUE TITLE
Changing stereotype does not remove the old one

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#256]
When I change a stereotype "typ vlastnosti" to "typ vztahu" and publish the workspace, the resulting model contains both stereotypes instead of removing the old one and leaving only the new one. This could be a generic problem for all stereotypes, not just "typ vlastnosti".

![image](https://user-images.githubusercontent.com/4235208/113744396-fc179780-9704-11eb-8342-0e329e30b27c.png)

**Comment by bindeali** [comment]
Could you elaborate on the scenario a bit more, please? I tried it locally and in `slovník-test` with https://xn--slovnk-test-scb.mvcr.gov.cz/modelujeme/workspace/instance2011031447 but the database always reflects the correct situation.
![image](https://user-images.githubusercontent.com/56399637/113980106-63893080-9846-11eb-94dc-691e95fb3d39.png)

**Comment by martinnec** [comment]
The problem does not appear anymore.
