### ISSUE TITLE
After changing title of a term the node cannot be deleted

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#26]
After changing a title of a term its bounding box keeps it size, although the node shrinks, see e.g.
![image](https://user-images.githubusercontent.com/1140626/77209356-5e075e00-6afe-11ea-9f63-6f606f620bb6.png)

This causes several problems:
- since 'i' and 'x' buttons disappear from the corners of the orange rectangle once your mouse exits the white area of the term. This makes the term effectively undeletable and its detail undisplayable
- the links have strange source and target points, which do not start at the border of the rectangle, see the following pics:
![image](https://user-images.githubusercontent.com/1140626/77209612-f867a180-6afe-11ea-98bf-57ce32a08c8b.png)

**Comment by bindetad** [comment]
Both of these should be fixed in 8c50b84f79428ae2292d49d18b99d7a4616fdb70. The links start and end at borders.

**Comment by psiotwo** [comment]
checked.
