### ISSUE TITLE
Creating a link to the same node makes the link undeletable

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#27]
When I create a link from one node to the same node, it will render as 

![image](https://user-images.githubusercontent.com/1140626/77327865-0e05e280-6d1c-11ea-9615-140d49456a32.png)

The buttons 'i' and 'x' do not appear for such link, making it undeletable. Also I didn't find a way to change the geometry of the link to make it visible (e.g. a circular or rectangular loop).

**Comment by bindetad** [comment]
As of 00526fe26fc67d265b358ce5e5b98e21e5f78ff1, a loop is automatically created, making deleting or adjusting the link easier.

**Comment by psiotwo** [comment]
Works fine. 

**Bug1:** Only if I hide an object from a diagram and then reintroduce it (by dragging from Packages view), the edge is collapsed again. But I was able to generate the loop you mention by clicking on it

**Bug2**: I am not sure how it is connected to this bug, probably not, but left-clicking a mouse while  Shift is pressed creates a new edge+label completely without a node (it is floating on the canvas).

**Comment by bindetad** [comment]
As of 2ee4729e2ccb001dd51d8ad0c9cef5265318ed6b I seem to have fixed the two bugs mentioned.

**Comment by psiotwo** [comment]
checked.
