### ISSUE TITLE
Replace Stereotype table in term detail with a clickable link similar to termit

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#29]
Instead of 
![image](https://user-images.githubusercontent.com/1140626/77521450-fd23b100-6e82-11ea-8348-e4370b5f9fad.png)

We should show:

Objekt↱

where the arrow is the hypertext link going to https://slovník.gov.cz/základní/pojem/objekt

**Comment by bindetad** [comment]
As of 00526fe26fc67d265b358ce5e5b98e21e5f78ff1, the link is in the detail (right) panel.
* Should I put it in more places?
* Clarification: should the arrow only appear on hover or all the time?

**Comment by psiotwo** [comment]
More places: Tab 'Connections' -> 'Using link' would benefit from this visualization as well.
On hover: I propose to have it on hover all the time for now, as the hyperlink would not be used so often and might be distracting for the modeler.

**Comment by bindetad** [comment]
In 2ee4729e2ccb001dd51d8ad0c9cef5265318ed6b I put the link in the Connections tab and changed it to appear on hover.

**Comment by psiotwo** [comment]
checked.
