### ISSUE TITLE
Deleting element does not remove subClassOf relations?

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#291]
I noticed that there are no RDF statements with 

https://slovník.gov.cz/agendový/104/pojem/využívá-isvs

as a subject. But it is an object of subClassOf. I know that I removed this element from the model. Through the OG UI I cannot see it anymore but it still remains in the model as an object of these RDF statements. This leads me to a question whether everything related to an element is correctly removed from the model.

**Comment by bindeali** [comment]
There is one finding that is a bug and one bug that might be the fault of my assumptions or the design. As for the first bug, it is true that OntoGrapher deletes triples only from the term's write-enabled vocabulary workspace copy (in this case, 104), so if the subClassOf triples were in a write-enabled 365/2000 vocabulary workspace copy, they were incorrectly kept in place. That is something I can fix right away.

If, however, the triples you were talking about were from the canonical 365/2000 vocabulary (i.e. the vocabulary was not added as a write-enabled workspace vocabulary copy), then this is something I actively avoid, as my assumption was that these vocabularies are not to be mutated. This is something that may require a discussion.

I assume the specific case you are talking about is the second one, as the triples are from the canonical contexts.
![image](https://user-images.githubusercontent.com/56399637/124932161-211cee80-e003-11eb-8115-713ca96b1e57.png)

**Comment by bindeali** [comment]
UPDATE: we have decided to create a warning prompt on deletion if such a relationship is detected for now.
