### ISSUE TITLE
Layout diagramu není na začátku editace udržen

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#292]
Postup:

Precondition : ve WS existuje jeden nebo více diagramů

1) Vytvořím nový diagram.
2) Vložím do něj prvky ze slovníků a rozmístím si je na diagramu jak potřebuji.
3) Přepnu na jiný diagram.
4) Vrátím se na můj nový diagram z 2).
5) Layout je rozházený.
6) Layout si spravím.
7) Provedu znovu 3) a 4).
8) Layout už je OK.

**Comment by bindeali** [comment]
Cannot seem to reproduce the issue in `slovník-test` version. Am I missing some steps?

https://user-images.githubusercontent.com/56399637/124936940-3e53bc00-e007-11eb-92d7-50f3e344f96c.mp4

**Comment by martinnec** [comment]
Seems that the problem does not appear anymore.
