### ISSUE TITLE
Managing of "source" cardinalities in data

### ISSUE THREAD

**Issue by bindeali** [opendata-mvcr/ontoGrapher#294]
## Problem statement
Consider the following image:
![image](https://user-images.githubusercontent.com/56399637/124018799-890e7c00-d9e8-11eb-9160-58efa6bc7fc4.png)
In the image above, there are cardinalities highlighted in red or yellow:
* Those highlighted in yellow - in the relationship target - are saved into the database as an owl:Restriction of owl:max/minQualifiedCardinality.
* Those highlighted in red - in the relationship source - are ONLY saved into the ontoGrapher context, and therefore any cardinalities here are not merged via pull requests in any way - as such, they are not available in another workspace in any way other than reintroducing them manually.

(This description holds for any type of relationship between any two terms.)

The enhancement, then, is enabling of saving the cardinalities in red and subsequently their loading from the vocabularies again.

## Enhancement description
A proposed implementation of this is an introduction of "inverse" relationships, i.e. a relationship that's in "the other direction" as the original, and therefore instead of saving cardinalities in the relationship source of the original (red), we save the cardinalities in the relationship targets (yellow) of both relationships.
![image](https://user-images.githubusercontent.com/56399637/124020452-988ec480-d9ea-11eb-93b5-e2e3bc1f5ab0.png)
Consider the image above. Let's say we created the relationship at the top, i.e. the one FROM the relationship type TO the object type. The relationship at the bottom would be created automatically, however, it would be **invisible** to the user (only the relationship on the top would be visible - this image is only for demonstration purposes of the underlying logic). The cardinalities saved to the vocabulary would still be the yellow ones, but because we have yellow cardinalities on both sides, the "source" and the "target" cardinality would both be saved.

Whenever the original source cardinality (red, at the top) is changed, the changes will be made to the inverse relationship's target cardinality in the data (yellow, at the bottom). The function of manipulating the target cardinality is unchanged.

The changes involved in developing this enhancement are:

1. Creating the inverse relationship automatically and creating a tether to the original relationship.
2. Using the tether to update the cardinalities/relationships predictably, e.g. to prevent duplicates etc.
3. Fetching the relationships and correctly decoding what is the original and what is the inverse, and then showing ONLY the original. 

(It's totally possible that this is horribly confusing - if so, I can try to explain it in another way. Questions and suggestions welcome.)

**Comment by psiotwo** [comment]
Proposal for the logic:

Oznamovatel [m1,M1]     <---má-vztažený-prvek-2---     [m2, M2] má oznamovatele

```
má-oznamovatele ⊑ 
    (≥ m1 má-vztažený-prvek-2 ⋅ Oznamovatel) 
  ⊓ (≤ M1 má-vztažený-prvek-2 ⋅ Oznamovatel)

Oznamovatel ⊑ 
    (≥ m2 (má-vztažený-prvek-2)-¹ ⋅ má-oznamovatele) 
  ⊓ (≤ M2 (má-vztažený-prvek-2)-¹ ⋅ má-oznamovatele)

```
