### ISSUE TITLE
Manuální tvorba stereotypu nic nedělá

### ISSUE THREAD

**Issue by ledsoft** [opendata-mvcr/ontoGrapher#3]
Pokusím-li se vytvořit nový stereotyp manuálně (a obejdu #2 tím, že nevyplním description), při kliknutí na tlačítko "Add stereotype" se nic nestane. Ani konzole prohlížeče nehlásí žádnou chybu.

**Comment by bindetad** [comment]
Issue je v 544c4ea605c7f56fc5bbbba42b683a20a53da11e opraven, uzavírám.

**Comment by martinnec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontoGrapher #1](https://trello.com/c/RCIYuzZP/22-pr%C3%A1ce-na-issues-v-ontographer-1)

**Comment by blcham** [comment]
"Stereotype" menu item was replaced by "Classes" and "Relationships" menu items. The bug is reproducible in both of them. Thus this ticket should be reopened.

**Comment by blcham** [comment]
Checked.
