### ISSUE TITLE
Minor UI tweaks

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#30]
- replace "delete name" with the delete icon currently used for deleting nodes from the diagram
- replace the delete icon currently used for deleting nodes from the diagram with crossed-out eye icon (to emphasize we are hiding the object, not deleting it)
- restyle the package tree/stereotype list to be more compact (similarly to an IDE class/package view)
- rename 'Titles' to 'Labels' (Názvy)
- remove header from 'Titles' table
- rename 'Item info' to 'Types' (Typy)
- rename 'Descriptions' to 'Definitions' (Definice)

**Comment by bindetad** [comment]
As of 00526fe26fc67d265b358ce5e5b98e21e5f78ff1, in order of the list:
* Implemented
* Implemented
* Not sure how much I should imitate views in e.g. JetBrains applications. I have made the text smaller, is there anything else I should do?
* Implemented
* Implemented
* Implemented
* Implemented

**Comment by psiotwo** [comment]
Checked.
