### ISSUE TITLE
Allow assign new stereotypes to existing nodes

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#31]
Currently a stereotype can be assigned to a class only upon creation (by dragging the stereotype to the diagram).

But it is possible that a class will need to have multiple stereotypes, e.g.:
- Typ objektu
- Druh

This task is to support assigning/changing stereotypes for an existing node in the node detail view.

**Comment by bindetad** [comment]
As of 27c2511, the detail panel allows the deletion or inclusion of additional stereotypes.

**Comment by psiotwo** [comment]
checked.
