### ISSUE TITLE
Show SKOS details of a term in the 'detail panel'

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#32]
Show in the detail panel the following glossary attributes:
- skos:prefLabel (cs, en)
- skos:definition (cs, en)
- skos:inScheme (cs, en) (Vocabulary/Slovník)

This would mean also aligning the data structures of 'models'/'packages' and diagram nodes into a single representation.

**Comment by bindetad** [comment]
Implemented as of 00526fe26fc67d265b358ce5e5b98e21e5f78ff1.

**Comment by psiotwo** [comment]
Labels and skos:prefLabel should be one merged.

**Comment by bindetad** [comment]
Is the current status (2ee4729e2ccb001dd51d8ad0c9cef5265318ed6b) what you meant?

**Comment by psiotwo** [comment]
Almost :-). Everything is fine except that upon changing the label I am again getting problems with the boundary of a node (once it resizes based on the label length). The boundary is again bigger than the visible area, making the edge start a bit aside (which is not such a big problem per se), but also 'i' and 'hide' buttons are not clickable anymore.

![image](https://user-images.githubusercontent.com/1140626/77957361-ab8c8380-72d3-11ea-922f-9304bd20868f.png)

**Comment by bindetad** [comment]
Hopefully the issue is fixed as of cf34905 -- I can't seem to reproduce it now.

**Comment by psiotwo** [comment]
fixed.
