### ISSUE TITLE
Export vybraného synonyma pro pojem do modelu

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#329]
Bylo by možné exportovat do modelu při publikaci slovníku i vybrané synonymum pojmu v OntoGrapheru? Vědět, jaké synonymum chce autor pro zobrazování v ontographeru by se hodilo i mimo ontographer - např. v generátoru schémat, ve formulářích, atd.

**Comment by psiotwo** [comment]
Varianty:
1. použít skos:hiddenLabel. Výhodou by byla editovatelnost i v TermItu. Nevýhoda - porušuje to constraint S13 SKOS specifikace
2. použít dc:title. Sémanticky to není daleko, ale tato property je dost obecná
3. vytvořit nový predikát.

S @bindeali se kloníme zatím nejvíc k **dc:title**. Nápady vítány.

@martinnec @MichalMed

**Comment by psiotwo** [comment]
Ještě teda varianta 
1b. použít skos:hiddenLabel tak aby neporušoval S13 - tedy label by byl do hiddenLabelu přesunut, nikoliv zkopírován.

**Comment by martinnec** [comment]
dc:title mě připadá rozumný.
