### ISSUE TITLE
SKOS export of the model

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#33]
Allow exporting model to SKOS format (serialized in RDF/Turtle) compliant with 

https://opendata.gov.cz/_media/dokumenty:s%C3%A9mantick%C3%BD-slovn%C3%ADk-pojm%C5%AF:c1v2d1_n%C3%A1vrh_koncepce_s%C3%A9mantick%C3%A9ho_slovn%C3%ADku_pojm%C5%AF.pdf

**Comment by bindetad** [comment]
Will the rdf:type be anything other than z-sgov-pojem:model (as well as owl:Ontology)? Also, what IRI should the project have? I have left it up to the user for now, but I imagine such information will be generated based on the project context in the future.

**Comment by psiotwo** [comment]
rdf:type is a generic typing link. So in glossary you can find different statements with the predicate of rdf:type. Some examples follow:

:glosář a z-sgov-pojem:glosář, skos:ConceptScheme, owl:Ontology .
:model a z-sgov-pojem:model, owl:Ontology .
:term1 a skos:Concept .
:term2 a skos:Concept .

**Comment by bindetad** [comment]
My question was perhaps worded a bit unclearly, I apologise. I understand what rdf:type is and what it means. I am going off section 4.4.1 (page 44) in the [.pdf you sent](https://opendata.gov.cz/_media/dokumenty:s%C3%A9mantick%C3%BD-slovn%C3%ADk-pojm%C5%AF:c1v2d1_n%C3%A1vrh_koncepce_s%C3%A9mantick%C3%A9ho_slovn%C3%ADku_pojm%C5%AF.pdf). 

My question was if z-sgov-pojem:model should always be among the exported model's rdf:types or if there will be a scenario in which we would want to export the model with a different type than this specific one. In other words, should the types be (besides the knowledge structure) immutable or not. For example, I understand that we want to export

:model1
 a z-sgov-pojem:model, z-sgov-pojem:základní-struktura, owl:Ontology ;
... labels, imports ...

But would we ever want to export something like
:model2 a some-different-sgov:model, owl:Ontology ;
... labels, imports ...

also?

**Comment by psiotwo** [comment]
Ah I see ...Currently you can stick to the IRIs in the doc, there is no plan to support other schemata.

**Comment by bindetad** [comment]
Current bugs:
* Reversed domain and range of certain predicates
* Output contains outdated/duplicate terms

**Comment by bindetad** [comment]
Progress update: This is fixed as of 7060e7b, but I will do further testing tomorrow to make sure I haven't missed anything.

**Comment by psiotwo** [comment]
In this picture, `https://slovník.gov.cz/základní/Untitled-project/pojem/Typ-objektu` should be `https://slovník.gov.cz/základní/Untitled-project/pojem/aaaa`

![image](https://user-images.githubusercontent.com/1140626/79079219-21e6a800-7d0e-11ea-94b0-5cbfec2c6303.png)

**Comment by bindetad** [comment]
As of 9adaeef725e129ee1376a94a4c2e162efe50a32f, I get
![image](https://user-images.githubusercontent.com/56399637/79102677-79ffc780-7d6b-11ea-9b95-3207d38f09b2.png)
 given
![image](https://user-images.githubusercontent.com/56399637/79102700-84ba5c80-7d6b-11ea-8bad-64fbbefbfa16.png)

**Comment by psiotwo** [comment]
checked.
