### ISSUE TITLE
Unclear number of terms in vocabulary

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/ontoGrapher#334]
As can be seen in the screenshot, there are 2 terms in the light blue vocabulary. However, it shows 3/57
![image](https://user-images.githubusercontent.com/718827/139867332-3d61fb14-a852-4e3c-a366-23d4f8631248.png)

**Comment by MichalMed** [comment]
Vidím, že tam jsou teď zobrazeny dva pojmy. Jen asi úplně nechápu proč. Mohla bys mi to prosím vysvětlit @bindeali
