### ISSUE TITLE
Change IRIs of exported terms

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#35]
Currenlty IRIs have the form

`<http://example.com/ontoGrapher/1586336826369>`

They should be represented as follows:

`<https://slovník.gov.cz/<knowledge-structure>/<skos:prefLabel of the vocabulary without whitespace>/pojem/<skos:prefLabel of the concept without whitespace>`

**Comment by bindetad** [comment]
Progress update: This is implemented as of 7060e7b, but I will do further testing tomorrow to make sure I haven't missed anything.

**Comment by psiotwo** [comment]
checked.
