### ISSUE TITLE
Split Model export into a glossary and the model

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#36]
- glossary contains skos:prefLabel, skos:definition, "rdf:type skos:Concept"
- model contains the rest

As defined in 
https://opendata.gov.cz/_media/dokumenty:s%C3%A9mantick%C3%BD-slovn%C3%ADk-pojm%C5%AF:c1v2d1_n%C3%A1vrh_koncepce_s%C3%A9mantick%C3%A9ho_slovn%C3%ADku_pojm%C5%AF.pdf

**Comment by bindetad** [comment]
Progress update: This is implemented as of 7060e7bf274dfa328c04ccfef3e54769af49da1a, but I will do further testing tomorrow to make sure I haven't missed anything. Also, the "Generate TTL" button was removed; all you have to do to export is either access the dialogue and/or change the "Knowledge structure" select.

**Comment by psiotwo** [comment]
checked.
