### ISSUE TITLE
Subpackage creation is not visible

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#37]
When I create a new subpackage of an existing package, the new subpackage is created. However, no change is visible in the UI until I unfold the package. The UI should unfold the package automatically.

**Comment by bindetad** [comment]
As of 27c2511, the parent package automatically opens.

(Note: the component must be tested locally at this time, not on the deployed site [because of an issue](https://github.com/opendata-mvcr/ontoGrapher/issues/42#issuecomment-615424927) with #42 - the link contains more details.)

**Comment by bindetad** [comment]
Closing, as subpackages are no longer implemented.
