### ISSUE TITLE
Not clear how to create a new vocabulary

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#38]
I am not able to create a new vocabulary. I would expect that packages are vocabularies, but I cannot edit them as vocabularies and when I move something to a package or subpackage, the skos:inScheme of this something does not change (remains Z-SGoV).

**Comment by bindetad** [comment]
Currently, user-created packages are not vocabularies, but simply a way to organize your model's resources. At first, the models (as in V-SGoV, for example) were on a separate tab, but that is no longer the case as of #23. In a way, then, the entire project is the vocabulary. I will have a meeting with Petr on the subject of ontoGrapher soon, so this question will definitely come up and maybe an enhancement issue will be created out of it.

**Comment by psiotwo** [comment]
Closing in favour of https://github.com/opendata-mvcr/ontoGrapher/issues/42
