### ISSUE TITLE
Cannot add drag'n'drop concepts to the canvas

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#384]
In the workspace https://xn--slovnk-7va.gov.cz/modelujeme/v-n%C3%A1stroji/ontographer/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-748298988

I cannot add any element to the Canvas (e.g. Subjekt práva from V-SGoV). I can only create new concepts (without problems).

**Comment by bindeali** [comment]
Is this what you meant? I just tested it and it works just fine.

https://user-images.githubusercontent.com/56399637/150514300-c810aee7-c53e-4014-bf11-fe22aaace02c.mp4

**Comment by psiotwo** [comment]
Works now for me as well! (Not sure what the problem was, so closing this one)
