### ISSUE TITLE
Project save generates empty JSON

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#39]
I have a simple project shown on the figure:

![image](https://user-images.githubusercontent.com/4235208/79075062-ab877d00-7cf0-11ea-84eb-76ffc269aea6.png)

When I choose Project save, I get emtpy JSON:

![image](https://user-images.githubusercontent.com/4235208/79075077-be01b680-7cf0-11ea-88f4-80abe6008f17.png)

**Comment by bindetad** [comment]
Creating a structure similar to yours, I can generate a save JSON as of feb4920 now.
