### ISSUE TITLE
Empty diagrams loaded for a new workspace

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#393]
1. Create a new workspace with https://slovník.gov.cz/legislativní/sbírka/361/2000
2. Open OG.
3. There are 4 diagrams loaded which is correct. However, they are empty.

![image](https://user-images.githubusercontent.com/4235208/151605704-7658ed54-8b9f-4ad1-b9cb-cfa6160f539d.png)

When I refresh page (F5), diagrams are loaded correctly.

**Comment by MichalMed** [comment]
diagramy se načtou, ale nejsou tam žádné vztahy - to je správně?

**Comment by martinnec** [comment]
Potvrzuju - diagramy se načtou, ale bez vazeb. To je špatně. Nejen, že se nezobrazí, ale nejsou vůbec načteny. Čili je nutno tento issue pořešit znovu a lépe.
