### ISSUE TITLE
New relationship type switched to compact view incorrectly

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#396]
I created two new relationship types:

![image](https://user-images.githubusercontent.com/4235208/151673580-5cec5971-f1b7-4f22-abf2-1e460c56b9b8.png)

Switching to the compact view does not work correctly for them:

![image](https://user-images.githubusercontent.com/4235208/151673598-c05e6a50-c442-41a5-9dcf-97bf7c6c5a83.png)

After refreshing the page (F5), it works correctly.

**Comment by MichalMed** [comment]
při vytvoření nového vztahu ve full vypadá vše ok, po přepnutí do compact view se vypadá takto:
![compact-1](https://user-images.githubusercontent.com/3779672/155114683-5da36cfd-c462-427a-8617-91689d96dae2.png)

Po opětovném přepnutí do full view:
![full-2](https://user-images.githubusercontent.com/3779672/155114798-98185de9-4108-45f4-b165-16e5dda34ec7.png)

Při druhém přechodu do compact:
![compact-2](https://user-images.githubusercontent.com/3779672/155114851-d2e4ca27-ded0-423c-83e9-1b7811c3f616.png)

Full zůstává pořád stejně (špatně).
