### ISSUE TITLE
Relation not removed from diagram

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#397]
I deleted a relation "má-vztažený-prvek-1" and created a new one with the same source but different target. Then I published the workspace. After creating a new workspace and opening the original diagram, I can see both "má-vztažený-prvek-1" - the new one as well as the deleted one.

It is the model of l-sgov 361/2000. In https://github.com/opendata-mvcr/ssp/blob/master/content/vocabularies/l-sgov-sbírka-361-2000/l-sgov-sbírka-361-2000-model.ttl there is [l-sgov-sbírka-361-2000-pojem:má-držitele](https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/vocabularies/l-sgov-sb%C3%ADrka-361-2000/l-sgov-sb%C3%ADrka-361-2000-model.ttl#L3334) defined. Its "[má-vztažený-prvek-1](https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/vocabularies/l-sgov-sb%C3%ADrka-361-2000/l-sgov-sb%C3%ADrka-361-2000-model.ttl#L3365)" and "[má-vztažený-prvek-2](https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/vocabularies/l-sgov-sb%C3%ADrka-361-2000/l-sgov-sb%C3%ADrka-361-2000-model.ttl#L2254)" seem to be correct here. I do not see here the old "[má-vztažený-prvek-1](https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/vocabularies/l-sgov-sb%C3%ADrka-361-2000/l-sgov-sb%C3%ADrka-361-2000-model.ttl#L3775)".

When I create a new workspace with this vocabulary, one of the loaded diagrams is https://github.com/opendata-mvcr/ssp/blob/master/content/attachments/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3-příloha.ttl . This is correct, but it contains the old "[má-vztažený-prvek-1](https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/vocabularies/l-sgov-sb%C3%ADrka-361-2000/l-sgov-sb%C3%ADrka-361-2000-model.ttl#L3775)":

- https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/attachments/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3-p%C5%99%C3%ADloha.ttl#L1097
- https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/attachments/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3-p%C5%99%C3%ADloha.ttl#L1474
- https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/attachments/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3-p%C5%99%C3%ADloha.ttl#L1760
- https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/attachments/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3-p%C5%99%C3%ADloha.ttl#L2657
- https://github.com/opendata-mvcr/ssp/blob/efc4253682975006c74eab0492079382f244d68f/content/attachments/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3/instance-ab2dd14f-770b-4dac-8b1d-1b413a001cf3-p%C5%99%C3%ADloha.ttl#L3060

These should be removed from the diagram.

**Comment by MichalMed** [comment]
Replikace issue:
1) vytvořím nový workspace, v něm slovník "test-", udělám tam diagram a publishnu. 
2) udělám v diagramu změnu, od jednoho vztahu smažu má-vztažený-prvek-1 s cílem A a ze stejného zdroje vytvořím má-vztažený-prvek-1 k cíli B. Publishnu.
3) Smažu workspace, vytvořím nový workspace, naimportuji do něj stejný slovník.
4) V diagramu je pouze vztah do B.

Problém je, že to celé není hned, po publishi musím čekat cca dvě minuty, abych v novém WS mohl importovat slovník, stejně tak potom čekám cca dvě minuty, než se mi načte diagram.
