### ISSUE TITLE
Visualization of a selected relationship remains on the same location

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#40]
I selected a relationship and then moved one of the associated classes. I got this:

![image](https://user-images.githubusercontent.com/4235208/79075125-146ef500-7cf1-11ea-9f31-84ea6823fbaa.png)

**Comment by bindetad** [comment]
I can't seem to reproduce the issue. Here's what I tried:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/56399637/79105937-dfef4d80-7d71-11ea-8796-d1272ca87f49.gif)

**Comment by psiotwo** [comment]
Maybe related - when quickly moving the link, I was able to get to 
![image](https://user-images.githubusercontent.com/1140626/79194850-9106ee00-7e2d-11ea-9a41-47b47344559d.png)

**Comment by martinnec** [comment]
As I write in #41 , I had the association twice in the model. Maybe this caused the problem?

**Comment by bindetad** [comment]
As of 27c2511, the highlighting works a little differently, and so the rendering issues @psiotwo mentions should no longer happen.

**Comment by bindetad** [comment]
Closing on request from @martinnec as this has been resolved.
