### ISSUE TITLE
Some cardinalities not published into the model

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#400]
The problem is demonstrated on the testing instance workspace:

https://slovník-test.mvcr.gov.cz/modelujeme/workspace/instance2007702781

There is the following diagram:

![image](https://user-images.githubusercontent.com/4235208/151713652-55ab2f65-5717-449d-b975-322b264796c8.png)

In the published model

https://github.com/opendata-mvcr/ssp/blob/9d97c09b65ba24e11cf2285ec15d99386e938889/content/vocabularies/d-sgov-test-kardinalit-mane/d-sgov-test-kardinalit-mane-model.ttl

I can see the following cardinalities exported in the model:
- all target cardinalities
- all source cardinalities of "má-vztažený-prvek-2" and "má-vlastnost"

I cannot see the following cardinalities:
- all source cardinalities of "má-vztažený-prvek-1"

So, exporting cardinalities during publishing a workspace needs to be checked.

**Comment by bindeali** [comment]
@martinnec Try it in about 15 minutes (as there is some delay from merge to publishing) in slovník-test - redo the cardinalities, from then on they should be saved correctly.
