### ISSUE TITLE
Mouse interactions

### ISSUE THREAD

**Issue by bindeali** [opendata-mvcr/ontoGrapher#406]
A specific and recurrent complaint given during user testing is that the mouse interactions OntoGrapher implements are not very friendly. Below are some examples:

- Middle clicking for panning is not easily discoverable for newbies, so they end up moving around the model using the scroll wheel's zoom functionality.
- Shift + left mouse button to pan is even more unusual, so laptop users feel they are out of luck.
- Creating links by clicking on an element's on hover arrow and then on another element's on hover arrow is difficult to discover.

I propose starting a discussion below. I'll start.

**Comment by bindeali** [comment]
My proposal:

- Switch the multiselection and panning functionality - i.e. panning would be done with the left mouse button and selecting with the middle mouse button / shift + left mouse button.
- Look into ways to create links the "usual" way, i.e. clicking and dragging from element to element. Initially I didn't implement this since it doesn't play nice with moving elements with the left mouse button, but given the fact that [Rappid makes this possible through popup link tools](https://resources.jointjs.com/demos/kitchensink), it is definitely possible.

**Comment by bindeali** [comment]
@MichalMed's [suggestion](https://github.com/opendata-mvcr/sgov-assembly-line/issues/39#issuecomment-1031879523):

> změna ovládání tak, aby se plátno posouvalo pravým nebo levým tlačítkem, tím pádem ale budeme muset někam přesunout přidání pojmu.
> kouknul jsem, jak to řeší Modelio, které, taky posouvá prostředním. Mají docela elegantní řešení, a sice že při úrovni zoomu, ve které canvas neobsahuje všechny prvky, se dole a vpravo objeví scrollovací lišty, kterými můžeme posouvat.

That's definitely possible too.

**Comment by bindeali** [comment]
@karelklima's [suggestion](https://github.com/opendata-mvcr/sgov-assembly-line/issues/39#issuecomment-1031911307):

> Pravým tlačítkem se bude dělat selekce (nyní je to přidání pojmu na klik)
> Klik levým tlačítkem na canvas přidá pojem
> Klik a drag levým tlačítkem na element posouvá element
> Klik a drag levým tlačítkem na canvas posouvá canvas

We've had left click to create a term before, what I and others didn't like about it is that during observation of users, I noticed that they _constantly_ (several times per minute) triggered the term creation dialogue on accident. So in that I like my proposal above instead, but I am willing to change my mind.

**Comment by MichalMed** [comment]
Návrh od MMR:
`Tj. jen návrh, ale přišlo by mi vhodné:

   - Levý klik - selekce
   - Levý klik a drag - posun
   - Pravý klik (a třeba volba z menu do budoucna až bude víc voleb) -
   přidání (případně kontextové menu a přidání)

Myslím, že takto by se to chovalo jako většina aplikací a bylo to
intuitivní.`

**Comment by bindeali** [comment]
Znovu otevírám pro druhou část issue: implementovat pointer interakce (pro dotykové obrazovky a touchpady).
