### ISSUE TITLE
Allow changing workspace from UI

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#43]
Currently, workspace URI is configured on deploy. Add one more menu item to allow change the URI.

**Comment by bindetad** [comment]
As of ca4898f, there is a new File menu item, "Fetch workspace...". It includes a function to test the connection to the workspace, if the connection is successful, it outputs the context name along with associated vocabularies, if any.

**Comment by psiotwo** [comment]
Each repository can contain multiple workspaces. Unfortunately, current one contains just a single workspace which is dwelling in the named graph http://example.org/pracovni-prostor/metadatový-kontext-123. 

However, another workspace (e.g. http://example.org/pracovni-prostor/metadatový-kontext-123) could have existed in the same repository.

So in order to identify a workspace, we need:
- URL of sparql endpoint (does not need to be changeable from UI, just in configuration)
- named graph IRI (should be changeable in UI)

**Comment by bindetad** [comment]
I fixed the wrong input, sorry about that. Should be fixed in 12036c7.
