### ISSUE TITLE
Make Model details compliant with Class Details

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#44]
Currently, terms from imported vocabularies which are read-only, can be dragged into a diagram and their details appear as "Model details". 

This view should list stereotypes from the respective model (currently the stereotype is just the term itself which is not correct, e.g. "Fyzická osoba").

Also other attributes should be the same as those in "Class details" (view for newly created/editable classes), e.g. Attributes/Diagrams/Connections/Properties. Just not editable.

**Comment by bindetad** [comment]
Implemented as of ca4898f.

**Comment by psiotwo** [comment]
- cannot see Attributes and Properties Tab
- also the heading "Class Details" and "Model Details" might be the same. Maybe even the concept name in the current language instead
-

**Comment by bindetad** [comment]
Included aforementioned features to e2fe3711.

**Comment by psiotwo** [comment]
skos:prefLabel and skos:inScheme are switched in both views. They should be in the same order.

Also put human readable names (with the original IRI as a tooltip or link):
- skos:prefLabel should read as "Název" in czech and "Label" in English.
- skos:inScheme should read as "Ze slovníku"  in czech and "In vocabulary" in English.
- skos:definition should read as "Definice" in czech and "Definition" in English.

**Comment by bindetad** [comment]
Renamed and rearranged the panel elements in 3027c4e.

**Comment by psiotwo** [comment]
I have just noticed that also the tabs "Connections", "Attributes", etc. are in different orderings for Class and Model elements.

**Comment by bindetad** [comment]
Apologies, I will pay more attention next time. Rearranged in f9d712d.
