### ISSUE TITLE
Loading of model in compact representation into OntoGrapher

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#45]
Support loading of compact SSP models into OntoGrapher. 

A/C:
- model connections will be seen in the "Connections" tab of "Class details". It means loading and interpreting - rdfs:domain, rdfs:range and rdf:type (stereotypes).
- user can create a diagram and drag the model element into it. Whenever both domain/range elements are present in a diagram, the corresponding link is shown as well.

**Comment by bindetad** [comment]
Implemented as of ca4898f.

**Comment by psiotwo** [comment]
Could you point me to some example? Cannot see any connection.

**Comment by bindetad** [comment]
Území is the rdfs:domain of má část území, therefore this shows up in the connections:
![image](https://user-images.githubusercontent.com/56399637/80393877-639c5480-88b1-11ea-807e-ea7c76575068.png)
If you put Část území into the same diagram, the link is automatically created.
![image](https://user-images.githubusercontent.com/56399637/80393954-7b73d880-88b1-11ea-8a86-561393538541.png)

**Comment by psiotwo** [comment]
Yes, this works.

But if I try another example, I cannot see the link (neither in the "Connections" tab):
![image](https://user-images.githubusercontent.com/1140626/80471739-203ef600-8944-11ea-82ef-30a9ce463ca1.png)

**Comment by psiotwo** [comment]
Yes this works.

But for another example, I cannot see the connection, although the data contains the respective triple.
![image](https://user-images.githubusercontent.com/1140626/80472229-bc68fd00-8944-11ea-95f3-c194946fee3d.png)

**Comment by bindetad** [comment]
Noted, should be fixed in 3027c4e.
