### ISSUE TITLE
Support saving workspace into the endpoint

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#49]
- Content of each writeable model should be written to the corresponding "/aktuální" context ("/změny" context not considered yet) in the current workspace endpoint. 
- All changes should be done on the fly.
- Whenever an error occurs during save (e.g. connection lost) the user is notified in the UI that the last change was not persisted.
- Currently users are not logged in, so no provenance is stored along the model.
- test against https://onto.fel.cvut.cz:7200/repositories/kodi-pracovni-prostor-validace

**Comment by bindetad** [comment]
Implemented in 8ee5c42 for:
* types,
* prefLabels,
* definitions,
* connections (ex: Blok z-sgov-pojem:<connection> Budova).

**Comment by bindetad** [comment]
I can't seem to connect to the aforementioned repository, though, all attempts to access onto.fel.cvut.cz:7200 result in a timeout, both on my machine and on deploy. For what it's worth, I tested it extensively on a localhost exact copy, so it should map nicely, but I can't be sure. (Accessing onto.fel.cvut.cz is without issue for me.)

**Comment by psiotwo** [comment]
It should be fixed. 

Yet, I still seem to be getting timeout.

![image](https://user-images.githubusercontent.com/1140626/81667423-8ac35c00-9443-11ea-89fc-e641fc700a3a.png)

**Comment by psiotwo** [comment]
This ticket saves data in COMPACT form. Since OntoGrapher does not allow creating compact models in the UI, we decided to implement loading/storing of FULL repre into OntoGrapher.
