### ISSUE TITLE
Remove configuration dependency on V-SGoV

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#51]
V-SGoV should be treated as a normal vocabulary and should not be part of the configuration.

**Comment by bindetad** [comment]
Fixed in 8ee5c42. This can be evidenced by the fact that the loaded [vocabulary.json](https://github.com/opendata-mvcr/ontoGrapher/blob/master/src/config/Vocabularies.json) no longer contains V-SGoV.
