### ISSUE TITLE
Support for subclassing

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#54]
Support:
- creating UML subClasses in the diagram
- parsing `<A>` rdfs:subClassOf `<B>` as a UML subClassOf link from `<A>` to `<B>`
- serializing thereof.

**Comment by bindetad** [comment]
Implemented in #57, deploy here: https://deploy-preview-57--ontographer.netlify.app/ (I'm having issues with PR checks described in #57, but the deploy works fine.)

**Comment by psiotwo** [comment]
Works OK in the preview
