### ISSUE TITLE
Support for full visualization

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#55]
The goal is to split FULL visualization from COMPACT visualization. Every time user can see a diagram of only FULL visualization or COMPACT, but not combining both. Support for FULL visualization only is OK.

Loading of  FULL OWL/COMPACT OWL should be possible and is independent on the actual visualization (COMPACT/FULL).

Saving of FULL OWL is the only option.

**Comment by bindetad** [comment]
Implemented in #57, deploy here: https://deploy-preview-57--ontographer.netlify.app/ (I'm having issues with PR checks described in #57.)

**Comment by psiotwo** [comment]
Works OK in the preview
