### ISSUE TITLE
Fetching workspaces created by mission-control does not load its vocabularies

### ISSUE THREAD

**Issue by bindetad** [opendata-mvcr/ontoGrapher#59]
Mentioned examples:
* [kodi-uloziste-dev](https://graphdb.onto.fel.cvut.cz/resource?uri=https:%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fmetadatov%C3%BD-kontext%2Finstance30701954&role=context)
* [kodi-pracovni-prostor-validace](https://graphdb.onto.fel.cvut.cz/resource?uri=http:%2F%2Fexample.org%2Fpracovni-prostor%2Fmetadatov%C3%BD-kontext-123&role=context)

This is mainly due to how _validace_, the repository ontoGrapher's fetching capabilities were tested on, differs from _dev_. The main difference are as follows:

* In _validace_, the vocabularies can be found from the triples of the vocabulary context linked to the metadata context via _d-sgov-pracovní-prostor-pojem:odkazuje-na-kontext_, such as _d-sgov-pracovní-prostor-pojem:obsahuje-slovník_. However, _dev_'s vocabulary context [(link)](https://graphdb.onto.fel.cvut.cz/resource?uri=https:%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fslovn%C3%ADkovy-kontext%2Finstance-542393289) contains no triples with such a predicate, and the IRI of the vocabulary context is also the IRI of the repository graph with the vocabulary, which isn't true for _validace_. Therefore, we either need two ways for each context style or decide on one and throw out the other.
* The vocabulary context graph in _dev_ contains very few information about the vocabulary (no labels or definitions, etc. - just the types, subclasses and restrictions). Therefore, should we want to load this additional info, we need the original source (or mission-control could duplicate at least these mentioned triples to _dev_, if not all of them - if I'm not mistaken, this is currently being worked on).

Tagging @psiotwo just in case this doesn't get to you.

**Comment by psiotwo** [comment]
> Mentioned examples:
> 
> * [kodi-uloziste-dev](https://graphdb.onto.fel.cvut.cz/resource?uri=https:%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fmetadatov%C3%BD-kontext%2Finstance30701954&role=context)
> * [kodi-pracovni-prostor-validace](https://graphdb.onto.fel.cvut.cz/resource?uri=http:%2F%2Fexample.org%2Fpracovni-prostor%2Fmetadatov%C3%BD-kontext-123&role=context)
> 
> This is mainly due to how _validace_, the repository ontoGrapher's fetching capabilities were tested on, differs from _dev_. The main difference are as follows:
> 
> * In _validace_, the vocabularies can be found from the triples of the vocabulary context linked to the metadata context via _d-sgov-pracovní-prostor-pojem:odkazuje-na-kontext_, such as _d-sgov-pracovní-prostor-pojem:obsahuje-slovník_. However, _dev_'s vocabulary context [(link)](https://graphdb.onto.fel.cvut.cz/resource?uri=https:%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fslovn%C3%ADkovy-kontext%2Finstance-542393289) contains no triples with such a predicate, and the IRI of the vocabulary context is also the IRI of the repository graph with the vocabulary, which isn't true for _validace_. Therefore, we either need two ways for each context style or decide on one and throw out the other.

I can see
https://slovník.gov.cz/datový/pracovní-prostor/pojem/odkazuje-na-kontext e.g. in _dev_ for https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance30701954

> * The vocabulary context graph in _dev_ contains very few information about the vocabulary (no labels or definitions, etc. - just the types, subclasses and restrictions). Therefore, should we want to load this additional info, we need the original source (or mission-control could duplicate at least these mentioned triples to _dev_, if not all of them - if I'm not mistaken, this is currently being worked on).

They should be present in the vocabulary content - some of the current data are loaded from models, however, which does not contain any label however. https://graphdb.onto.fel.cvut.cz/resource?uri=https:%2F%2Fslovn%C3%ADk.gov.cz%2Fdatov%C3%BD%2Fpracovn%C3%AD-prostor%2Fpojem%2Fslovn%C3%ADkovy-kontext%2Finstance-542393289

**Comment by bindetad** [comment]
Progress update: I can now load vocabularies from mission-control work-spaces in branch `latest`, I will do more testing today in the afternoon to see if saving functions etc. are unaffected. I'll notify when I deploy it so you can take a look at it.

**Comment by bindetad** [comment]
So, it seems like I have implemented the feature in branch `latest`, but I am a little confused on how (and when) mission-control creates the instance of the selected vocabulary, which prevents me from fully testing this. (Also, loading the workspace from mission-control is also implemented, but this won't be useful until the changes are merged into `master`, as mission-control understandably points to the master deploy.) 

My question is this: How do you initiate the copying of added vocabularies in mission-control? I have added some into an example workspace, but nothing seems to be happening on graphDB (i.e. the vocabulary context graph is not created and no vocabulary triples are brought over). Maybe I am inputting the wrong URIs?

Also, [MB private workspace](https://mission-control.netlify.app/workspaces/instance1599714395) is empty in mission-control and [V-SGoV](https://mission-control.netlify.app/workspaces/instance1116081026) doesn't seem to load at all. If I'm not mistaken,  mission-control is currently being worked on, so I'm not sure I can test much until any changes are done.

My testing workspace is [here](https://mission-control.netlify.app/workspaces/instance-1012983373).

**Comment by psiotwo** [comment]
Once a vocabulary is added to workspace, it is being loaded into the context.  For example, this workspace https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1839837489 contains some loaded vocabularies.

Currently, you have to add vocabularies of the form <VOC>/glosář or <VOC>/model.
