### ISSUE TITLE
Model management

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#6]
A user shall be able to import one or more existing models to a project. The import is done in the same way as the import defined in the default configuration (see #1 ).

There shall be a panel which shows the list of models in the project. It has two parts. 1st part contains imported models which are read only. 2nd part contains my own models. Each model is represented as a UML package which contains classes and associations of the model.

In the panel the user shall be able to unpack a model. The tool shows the list of classes in the model. For each class it displays its name. The user shall be able to drag a class and drop it on the canvas. For each pair of the classes on the canvas, all associations between them defined in any model are shown.

When a new class is created on the canvas, it does not belong to any package. In the panel with the package list it is added under the project root. The user shall be able to move a selected class to a selected model. Each class belongs to 0 or 1 model.

**Comment by martinnec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontoGrapher #1](https://trello.com/c/RCIYuzZP/22-pr%C3%A1ce-na-issues-v-ontographer-1)

**Comment by bindetad** [comment]
This feature is implemented as of b693b610b8797c4d349f5b25b63a3a8d040eb8b8 and described in #7.

**Comment by blcham** [comment]
> This feature is implemented as of [b693b61](https://github.com/opendata-mvcr/ontoGrapher/commit/b693b610b8797c4d349f5b25b63a3a8d040eb8b8) and described in #7.

As commented in #7, I am not able to test. Could you please describe scenario how to simulate it ?

**Comment by bindetad** [comment]
The gist of it is described in the wiki (particularly [here](https://github.com/opendata-mvcr/ontoGrapher/wiki/Basic-modeling) and [here](https://github.com/opendata-mvcr/ontoGrapher/wiki/Package-management) as well as in #7).

If you drag a class to the canvas, it appears in the root package. To create a package and move the class to it, click the Add button to create a package first:
![image](https://user-images.githubusercontent.com/56399637/70955565-a3387180-2071-11ea-8e0d-3976648fa5c2.png)
Then, you can manage the root package to move the class to your created package:
![image](https://user-images.githubusercontent.com/56399637/70955619-c82ce480-2071-11ea-8c16-8a0bd8148040.png)
In the manage dialogue, you can also see the connections to other classes, for example this:
![image](https://user-images.githubusercontent.com/56399637/70955667-f3173880-2071-11ea-9355-cc73c430d219.png)
can be seen as this:
![image](https://user-images.githubusercontent.com/56399637/70955686-03c7ae80-2072-11ea-913b-f50cf017d810.png)

**Comment by blcham** [comment]
I consider this simplification of model management to be closed. This simplification does not solve issues with reuse of classes across multiple models (still needs some discussion). 

Related issues: #14.
