### ISSUE TITLE
Loading of OWL constraints does not work

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#61]
The following workspace does load successfully into OntoGrapher, listing its glossary.

But, when I move two related term into a diagram, the corresponding link is not shown - e.g. "Je evidencí pro" and "Typ evidenčního systému".

https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1775747014

**Comment by bindetad** [comment]
How did you get `Typ evidenčního systému` onto the canvas? I can see that the relevant restrictions are displayed in the DB and processed in ontoGrapher, but the mentioned concept itself isn't in a vocabulary of the workspace's context (only a declaration of type), so there is no way to actually represent the relationship.

**Comment by psiotwo** [comment]
I updated VSGoV and still cannot see the links:
https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-534712305

**Comment by bindetad** [comment]
Progress update: I can see the links in `latest` (deploy: https://deploy-preview-62--ontographer.netlify.app/), but I will do more testing tomorrow before I call this fixed.
