### ISSUE TITLE
Newly created concepts have wrong URI

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#65]
I created Nový pojem in V-SGoV workspace:
![image](https://user-images.githubusercontent.com/1140626/86800709-9a41d880-c073-11ea-81e3-36ddb5fde6da.png)

But in GraphDB I can find it as 

https://slovník.gov.cz/datový/pracovní-prostor/pojem/slovníkový-kontext/pojem/Nový-pojem

while it should be 

https://slovník.gov.cz/veřejný-sektor/pojem/nový-pojem

**Comment by bindetad** [comment]
This issue is fixed in the master deploy.
