### ISSUE TITLE
Detail panel's connection tab is not immediately updated on creation of a new relation

### ISSUE THREAD

**Issue by bindetad** [opendata-mvcr/ontoGrapher#67]
If the connection tab is open, it is expected that a newly created relationship related to the concept in the panel is also reflected in the tab. Currently, this list is only refreshed only on re-selection of the aforementioned concept.

**Comment by bindetad** [comment]
In 2f5b5a1 on `master`, this issue seems to be fixed.

**Comment by karelklima** [comment]
Looks good to me

**Comment by bindetad** [comment]
Closing on request of @karelklima .
