### ISSUE TITLE
Zs-GoV concepts loaded as a vocabulary crash the app

### ISSUE THREAD

**Issue by bindetad** [opendata-mvcr/ontoGrapher#68]
If Zs-GoV is loaded as a vocabulary in the app, manipulating with such concepts crashes the app.

**Comment by bindetad** [comment]
As of b2966b2, I have not been able to replicate the issue.

**Comment by psiotwo** [comment]
Neither was I. Also created https://github.com/opendata-mvcr/sgov/issues/70 to solve this systematically.
