### ISSUE TITLE
Creating multiple identical relationships between the same two concepts is not disallowed

### ISSUE THREAD

**Issue by bindetad** [opendata-mvcr/ontoGrapher#69]
Currently, the user can create multiples of the exact same relationship between the exact same concepts, which is redundant. Expected behaviour is to disallow creation of such duplicates.

**Comment by bindetad** [comment]
With the UI redesign #71, creating duplicate relationships in this way should be impossible.

**Comment by karelklima** [comment]
Works as expected, I am not able to create multiple identical relationships between the same two concepts.

**Comment by bindetad** [comment]
Closing on request of @karelklima .
