### ISSUE TITLE
Deleting a relationship in one diagram does not delete it in other diagrams

### ISSUE THREAD

**Issue by bindetad** [opendata-mvcr/ontoGrapher#70]
Deleting a relationship should be reflected in other diagrams, however, currently the relationship stays in other diagrams, despite the fact that the connections tab accurately displays the current situation pertaining to the concept's relationships.

**Comment by bindetad** [comment]
In 2f5b5a1 on `master`, I have fixed the issue as well as the reverse bug (newly created relationships appearing on other diagrams).

**Comment by karelklima** [comment]
Works as expected, if the relationship is deleted in one diagram, it disappears from the others as well.

**Comment by bindetad** [comment]
Closing on request of @karelklima .
