### ISSUE TITLE
Cannot move blank node to diagram

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#72]
1. I load https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1367101712 into OntoGrapher
2. I click to the diagram to create a new blank node
3. I hide the node (and can see it with "hidden icon" in the left panel)
4. I cannot drag and drop this node back to the diagram - the blank node does not appear there upon drop.

**Comment by bindetad** [comment]
Should be fixed in the #74 Detail panel deploy.
