### ISSUE TITLE
Cannot open V-SGoV workspace from Control panel in OntoGrapher

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#73]
The workspace V-SGoV (https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-92687985) does not load in OntoGrapher.
![image](https://user-images.githubusercontent.com/1140626/88159016-093f3580-cc0d-11ea-9550-b7fc81cd7e40.png)

**Comment by bindetad** [comment]
This is an issue that seems to be already fixed with the referenced 0d7b781 commit.

**Comment by ledsoft** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Aktualizace TermIta z nejnovější open-source verze ČVUT.](https://trello.com/c/0VDvyVdw/189-aktualizace-termita-z-nejnov%C4%9Bj%C5%A1%C3%AD-open-source-verze-%C4%8Dvut)
