### ISSUE TITLE
Cannot see existing relators

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#75]
I cannot see links between Fyzická osoba and  Křestní jméno, but it exists in data.

https://github.com/opendata-mvcr/ssp/blob/2405bebf76f3f1cdcf08cab9ed630c5cdcf9d92e/v-sgov/v-sgov-model.ttl#L258

https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1077205419

![image](https://user-images.githubusercontent.com/1140626/88704461-61df6880-d10e-11ea-8e06-832b18f6b80e.png)

**Comment by bindetad** [comment]
This should be resolved in the ´master´ deploy as of 60a79d7.

**Comment by psiotwo** [comment]
Now I can see the 'ma vlastnost' links, but not subclass anymore. 
![image](https://user-images.githubusercontent.com/1140626/89259417-8d8cb200-d62a-11ea-8a7a-9fe4b55b9ea0.png)

**Comment by psiotwo** [comment]
Tried on a new workspace, and cannot reproduce - probably problem of data
