### ISSUE TITLE
Blank screen after refresh (not always)

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#76]
Upon refreshing a page, I got a blank screen
![image](https://user-images.githubusercontent.com/1140626/88766307-1661a480-d178-11ea-8ffd-ec8255f73de4.png)

**Comment by bindetad** [comment]
I have not been able to reproduce the issue, but I have modified the start-up sequence slightly in 2f5b5a1, so if you get the error again, let me know.

**Comment by psiotwo** [comment]
Unfortunately, the same error happened again. Typically this happens after some minutes of diagram editing and changing term details.

**Comment by bindetad** [comment]
The c444357 revision should be more crash-proof.

**Comment by psiotwo** [comment]
Looks OK, wasn't able to crash it in comparable scenarios now, so closing the ticket.
