### ISSUE TITLE
Cannot see some validation messages

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#77]
For example validating https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1107673637

produces a violation of node "Znalostní struktura" with message "More than 0 values have shape _:d89e40bc9481bfcfa80c63778ee04273". The violation is shown in the list, but the message is empty.

**Comment by bindetad** [comment]
This should be resolved in the `master` deploy as of 60a79d7.
