### ISSUE TITLE
The default vocabulary should be visualized

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#78]
When new nodes are being created, the user does not know which vocabulary are they put in. 

The goal of this ticket is to visualize the information about the default vocabulary to the user.

**Comment by bindetad** [comment]
In revision c444357, the visualization is done via a color change and tooltip on the default vocabulary on creation of a new concept.

**Comment by bindetad** [comment]
At least since fa9cf71, the concept of default vocabularies has been removed, since the user chooses the vocabulary on concept creation.

**Comment by psiotwo** [comment]
Reject. Not relevant any more.
