### ISSUE TITLE
Hidding elements on canvas

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#8]
For each element on the canvas of a diagram, there shall be a context menu with "Hide" option. When the user selects this option, the element is hidden in the diagram and it is not part of its visual layout. In other words, it is removed from the diagram but it remains in the model.

**Comment by bindetad** [comment]
The function is implemented as follows from 02bd39be12cc116ea261b575fd86c6914239e68a:
![image](https://user-images.githubusercontent.com/56399637/69137766-af0a3580-0abd-11ea-8d91-9c33af99a321.png)

**Comment by martinnec** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Práce na issues v ontroGrapher #2](https://trello.com/c/jjYcBXyE/65-pr%C3%A1ce-na-issues-v-ontrographer-2)

**Comment by bindetad** [comment]
The function has since changed. Now, hiding elements is done via selecting the element on the canvas and hitting the 'delete' key. To make it reappear again, drag it from the package tab back onto the canvas.

**Comment by blcham** [comment]
'Delete' key works.
Restoring layout for classes without relationships works.

Restoring layout for classes with relationships does not work and throws error `ReferenceError: node is not defined` as shown below.

1) creating classes with relationships:
![Selection_004](https://user-images.githubusercontent.com/3962237/71770705-10804980-2f30-11ea-97c9-950a05a08d00.jpg)

2) trying to drag&drop class "Untitled Akce" leads to error :
![Selection_005](https://user-images.githubusercontent.com/3962237/71770756-d19ec380-2f30-11ea-9039-4fef381c4cd2.jpg)

**Comment by bindetad** [comment]
Pushed out a hotfix for this in 59ca51be8c842a6cbfd8420e2b7a661475f36a5b.

**Comment by blcham** [comment]
Another issue is that restoring of class association does not work in cases when I restore the target class of the association before its source class.

Demonstration:
![g](https://user-images.githubusercontent.com/3962237/71787702-7d244280-301b-11ea-9b52-7bbe074b02a2.gif)

**Comment by bindetad** [comment]
Accidentally closed the issue because of a keyword in the commit message. The bug should be fixed in d3cd072a7ebb5f366932180a3eeca9240299d16a. 

It is possible that I will change the hiding trigger (i.e. from deleting the element on the canvas to a button or something else) as I work on the UI. If it comes to that, I will notify you so that you can reopen the issue if there are any problems. In any case, I will work on making sure that it is clear which elements are hidden and which are not in the panel.

**Comment by blcham** [comment]
Bug is still present.

**Comment by bindetad** [comment]
Accidentally switched a line before my last commit, sorry about that. b38d0650976fe92da3ce462e48a8d29df756c6bd produces the following behaviour:

![capture](https://user-images.githubusercontent.com/56399637/72688598-2fbecf80-3b09-11ea-856a-572d56bee140.gif)

**Comment by blcham** [comment]
checked.
