### ISSUE TITLE
Some connections are not shown in the diagram

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#80]
E.g. Křestní jméno lists several connections to Fyzická osoba in the term detail panel, yet they are not shown in the diagram once I drag there both classes.

![image](https://user-images.githubusercontent.com/1140626/89628889-3cd0bf80-d89d-11ea-83a9-3355bf3a201e.png)

**Comment by bindetad** [comment]
At least since fa9cf71, this connection is established.

**Comment by psiotwo** [comment]
Tested, works OK.
