### ISSUE TITLE
Creating a new element by clicking on canvas is annoying

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#82]
When I click on an empty space on the canvas a new element with blank label is created. This is annoying. I would prefer a little more complicated way to create a new element with some intermediate click. But maybe this is just my problem so change this behavior only when more users agree on this.

**Comment by bindetad** [comment]
In a meeting, we decided that a good alternative is that instead of immediately creating a new concept, a dialogue box is shown prompting the user to enter a name for the concept before creation (this would also allow the user to cancel). What do you think?

**Comment by bindetad** [comment]
The aforementioned proposal has been implemented in the c444357 revision.

**Comment by martinnec** [comment]
OK, I agree.
