### ISSUE TITLE
Filtering possible kinds of a new relation between elements

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#83]
When I want to create a new relation, I click on the arrow button in the top-left corner and then I click on another element I want to connect. This is OK. Then I get the list of all types of relations. I would prefer only those which make sense from the UFO and Z-SGOV point of view. E.g., when I want to relate a "typ objektu" with a "typ vlastnosti" I would like to see only one possibility "má vlastnost". And when there is only one possibility, it shall be picked up automatically by the system.

**Comment by psiotwo** [comment]
Use property 'https://slovník.gov.cz/základní/pojem/charakterizuje' for the metatype, e.g. see https://slovník.gov.cz/základní/pojem/typ-vlastnosti.

**Comment by bindetad** [comment]
In fca1208, this feature is now implemented, though I have also included a "Display incompatible relationships" option in the relationship creation dialogue in case of any issues.

**Comment by psiotwo** [comment]
Checked. OK.
