### ISSUE TITLE
Terms created in ontographer are not properly saved to the workspace

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#86]
I added new elements in the workspace by adding them to a diagram in ontographer. They were not visible in Termit. I tried to reopen Termit from the mission control several times. I also renamed one element in ontographer and it was not renamed in Termit.

**Comment by bindetad** [comment]
Not sure exactly why this happens, as the term is properly renamed in the DB. I will ask about this in a meeting and report back.

**Comment by bindetad** [comment]
This is because Termit does not show immidiate changes in the DB, but rather loads from its cache, which is updated each session. So the changes will not be shown immidiately, but they will be shown eventually.

**Comment by psiotwo** [comment]
TermIt cache has been turned off. Thus TermIt is now slower, but fully up-to-date.

Still, when I save data in OntoGrapher, 
![image](https://user-images.githubusercontent.com/1140626/93477556-76183880-f8fb-11ea-8e26-214dd4107977.png)

I could not see them in TermIt, so I looked in the GraphDB and cannot see the change there persisted:
![image](https://user-images.githubusercontent.com/1140626/93477750-b081d580-f8fb-11ea-8eeb-630d5e6ad3b5.png)

**Comment by bindetad** [comment]
As of e894a89 this issue seems to be resolved (it is related to #106).

**Comment by psiotwo** [comment]
Now I cannot create any term in a workspace. This is what I see after clicking to canvas and filling the label of a new concept.
![image](https://user-images.githubusercontent.com/1140626/94535715-2e21db80-0242-11eb-8268-f36542a77910.png)

**Comment by bindetad** [comment]
I have remedied the crash in 4522574.

**Comment by psiotwo** [comment]
Creation works, but the newly created concept does not have type of skos:Concept
![image](https://user-images.githubusercontent.com/1140626/94549063-eacf6900-0251-11eb-9234-a9eb0f21ba6d.png)

**Comment by psiotwo** [comment]
When I try to create a new concept in 

https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-261118310

I can see 
![image](https://user-images.githubusercontent.com/1140626/95329467-48456480-08a7-11eb-9eeb-52205b47bafa.png)

But having the selection intact (choosing vocabulary of contacts, not V-SGoV), the term still ends up in V-SGoV
![image](https://user-images.githubusercontent.com/1140626/95329527-64e19c80-08a7-11eb-82d9-6166e410e78f.png)

Furthermore, I cannot see the term persisted in GraphDb

**Comment by bindetad** [comment]
This issue is fixed in fca1208.

**Comment by psiotwo** [comment]
Checked, looks good. A followup ticket for serialization of concepts in general is #122
