### ISSUE TITLE
Connections in all diagrams in workspace lost

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#88]
I had a workspace with 3 diagrams and on one of them I clicked on an empty space on the canvas. A blank element was created. I wanted to remove it but the attempt was unsuccesfull (the message was shown in the top left corner). Ontographer offered me to try again so I tried but I have received a blank page. I closed the tab with ontographer and reopened the workspace in ontographer from the mission control. I got all diagrams without connections:

![image](https://user-images.githubusercontent.com/4235208/90313288-adb25000-df0b-11ea-8d7e-aa17fe6e0c18.png)

**Comment by bindetad** [comment]
As of b2966b2, the relevant code has been updated, so that the retry crash should not happen again. I have not been able to replicate the "diagrams without connections" part, so if that happens, please let me know.

**Comment by psiotwo** [comment]
Wasn't able to reproduce the wrong behaviour either. But, when I disconnect the network, I am still able to update the diagram and there is no warning/info that I am doing work that will be lost ... E.g. a connection status indicator + read-only mode whenever disconnected might be useful.

**Comment by martinnec** [comment]
I cannot reproduce it as well. And I agree with @psiotwo .

**Comment by psiotwo** [comment]
Closing this one in favour of https://github.com/opendata-mvcr/ontoGrapher/issues/108
