### ISSUE TITLE
Hiding connections

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#89]
I can remove a connection in a diagram. I do not know whether it means its complete removal from the model or just hiding in the diagram. I would prefer to have two options - remove (the current button) and hiding.

**Comment by bindetad** [comment]
Currently, hiding is only possible for concepts; clicking on the red cross button on a connection deletes it completely. Technically, you can 'hide' a connection by hiding the concept connected to it, and bring it back by putting the given concept back. In my opinion, including an option to hide a connection individually seems like it would be confusing for the user, as they would also have to (have an option to) check which connections are hidden and which ones aren't (or don't exist outright). There are possible UI enhancements to make it more intuitive, but I'm not sure how useful it would be.

**Comment by martinnec** [comment]
Seems reasonably but lets wait for the other's opinions.

**Comment by psiotwo** [comment]
I think "delete" semantics is adequate here at this point, both for FULL and COMPACT view at this point, IMO.

**Comment by psiotwo** [comment]
Closing after discussion - no viable short-term solution. Will be resolved as a part of rethinking of the modeling UX -see #107
