### ISSUE TITLE
No connections shown for a relator type with connections

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#91]
When I put a relator type with its two related object types defined in the model into a diagram, corresponding connections are not shown. E.g.:

![image](https://user-images.githubusercontent.com/4235208/91638252-2cc87d80-ea0e-11ea-81bd-f21fbc39387e.png)

**Comment by bindetad** [comment]
At least since fa9cf71, I can see the connection. Here's what I tried on a new workspace: 
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/56399637/92878861-caf41480-f40c-11ea-855b-c11501d25684.gif)

**Comment by psiotwo** [comment]
Still the same issue for me:
![image](https://user-images.githubusercontent.com/1140626/93270501-963be080-f7b1-11ea-8af2-f26bf1d77023.png)

URL: https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1771937413

**Comment by bindetad** [comment]
With 935e361 (and resetting of this workspace's saved data), this is what I see:
![image](https://user-images.githubusercontent.com/56399637/93353874-b2389400-f83c-11ea-86a6-cc5f42bdf440.png)

**Comment by psiotwo** [comment]
OK, works for me, closing.
