### ISSUE TITLE
Cardinalities are inconsistent between full/compact

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#92]
There is some mismatch between cardinalities in the two views of the same relationship. See below

![image](https://user-images.githubusercontent.com/1140626/91939064-73abc100-ecf5-11ea-9215-f1bf3be8c01e.png)
![image](https://user-images.githubusercontent.com/1140626/91939091-7efeec80-ecf5-11ea-90ee-576031e316f0.png)

**Comment by bindetad** [comment]
In fa9cf71, this issue should be fixed.

**Comment by psiotwo** [comment]
ok.
