### ISSUE TITLE
Editing relationships inconsistent between FULL/COMPACT view

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#93]
1. start with full view
2. edit the name of a relationship (opens the right panel)
3. switch to compact view - the right panel seems is still open
4. use the existing right panel to edit the relationship name (of a relationship now visualized as an edge in compact view).

Upon completing 4. - The message "Saving" is hanging forever.

![image](https://user-images.githubusercontent.com/1140626/91939314-e4eb7400-ecf5-11ea-96da-e832192145ec.png)

**Comment by bindetad** [comment]
In fa9cf71, the detail panel is closed on representation switch.

**Comment by psiotwo** [comment]
ok.
