### ISSUE TITLE
Switching from compact to full view does not show properties

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#95]
When I switch to the compact view, properties ("typ vlastnosti") are hidden and binary relationships ("typ vztahu") are replaced with a UML association. When I switch back to the full view, properties are not shown - remain hidden. I have to place them to the canvas again. I do not see any possibility of how to show them where they were originally.

When I switch from full to compact, I get

![image](https://user-images.githubusercontent.com/4235208/92585225-f81db700-f294-11ea-8818-df04d364caa7.png)

When I switch to full back, I get

![image](https://user-images.githubusercontent.com/4235208/92585286-0b308700-f295-11ea-905a-adaa0d338b1b.png)

**Comment by martinnec** [comment]
And I noticed another problem here - as can be seen on the second screenshot, "má požadovanou kvalifikaci" is shown on the diagram but marked as hidden on the left.

**Comment by bindetad** [comment]
As of b2966b2, switching should show properties again.

**Comment by psiotwo** [comment]
I still experience strange behaviour - https://ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1771937413:

1) Full view - OK
![image](https://user-images.githubusercontent.com/1140626/93474024-16b82980-f8f7-11ea-9a10-ae4a624713c6.png)

2) Removed extra point  - OK
![image](https://user-images.githubusercontent.com/1140626/93474110-36e7e880-f8f7-11ea-8211-f155e487772c.png)

3) Switched to compact - the property should not be shown
![image](https://user-images.githubusercontent.com/1140626/93474249-639c0000-f8f7-11ea-9734-adaafb640671.png)

4) Switched back to full - the point I removed in step 2 is there again
![image](https://user-images.githubusercontent.com/1140626/93474326-7b738400-f8f7-11ea-9285-bd91b0ac3978.png)

**Comment by bindetad** [comment]
As of e894a89 this issue seems to be resolved (I have made changes to link vertex saving).

**Comment by psiotwo** [comment]
I can see the property types all the time. Which is currently OK, an improvement is needed here, as discussed in
https://github.com/opendata-mvcr/ontoGrapher/issues/96.

So closing this one.
