### ISSUE TITLE
Compact view should look as as a UML class diagram as simple as possible

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#96]
I propose the following changes to the compact view. Or if you insist on the current form of the compact view then I propose another kind of view (I do not know how to call it):

- no stereotypes shown
- property types ("typ vlastnosti") shown but not as UML classes but as UML attributes (inside the box of the owning class)

This will be usefull, e.g., in OFN documentation.

**Comment by psiotwo** [comment]
I agree - we should extend compact towards UML attributes. 
Re: stereotypes, I propose to have another switch allowing to show/hide stereotypes both in FULL/COMPACT.
