### ISSUE TITLE
Line breaks are not stored

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/ontoGrapher#97]
I have this diagram where the generalization line from "Pracoviště" to "Věc" has two breaks:

![image](https://user-images.githubusercontent.com/4235208/92589151-6f097e80-f29a-11ea-8abc-5853e383a72f.png)

When I reopen it from the mission control, I get the diagram without breaks:

![image](https://user-images.githubusercontent.com/4235208/92589196-82b4e500-f29a-11ea-9d2f-96a4e1ba6cf2.png)

**Comment by bindetad** [comment]
As of b2966b2, vertices (line points) are stored and loaded from the DB.

**Comment by psiotwo** [comment]
Tested, works OK, closing.
