### ISSUE TITLE
Restrict vocabulary selection to R/W vocabularies only

### ISSUE THREAD

**Issue by psiotwo** [opendata-mvcr/ontoGrapher#98]
Upon creating of a new box (click in canvas) I am offered a dialog where I can select a vocabulary in which the term will be created.

This is OK, but only R/W vocabularies should be shown. For example, if my workspace looks like 
![image](https://user-images.githubusercontent.com/1140626/92649997-2e3a5580-f2ec-11ea-9f91-e38932479d09.png)
I would expect to see only "Slovník vyhlášky č. 82/2018 Sb. (o kybernetické bezbečnosti)" in the vocabulary selection options.

**Comment by bindetad** [comment]
As of b2966b2, the selection is restricted to RW vocabularies.

**Comment by psiotwo** [comment]
Tested, LGTM
